

class CitiesStatesCountries {
  static List<String?>? countriesCities = [
    "New York",
    "New Jersay",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San Jose",
    "Austin",
    "Jacksonville",
    "Fort Worth",
    "Columbus",
    "Indianapolis",
    "Charlotte",
    "San Francisco",
    "Seattle",
    "Denver",
    "Oklahoma City",
    "Nashville",
    "El Paso",
    "Boston",
    "Las Vegas",
    "Portland",
    "Detroit",
    "Louisville",
    "Memphis",
    "Baltimore",
    "Milwaukee",
    "Albuquerque",
    "Fresno",
    "Tucson",
    "Sacramento",
    "Mesa",
    "Kansas City",
    "Atlanta",
    "Omaha",
    "Colorado Springs",
    "Raleigh",
    "Virginia Beach",
    "Long Beach",
    "Miami",
    "Oakland",
    "Minneapolis",
    "Tulsa",
    "Bakersfield",
    "Wichita",
    "Arlington",
    "Aurora",
    "Tampa",
    "New Orleans",
    "Cleveland",
    "Anaheim",
    "Honolulu",
    "Henderson",
    "Stockton",
    "Lexington",
    "Corpus Christi",
    "Riverside",
    "Santa Ana",
    "Orlando",
    "Irvine",
    "Cincinnati",
    "Newark",
    "Saint Paul",
    "Pittsburgh",
    "Greensboro",
    "St. Louis",
    "Lincoln",
    "Plano",
    "Anchorage[",
    "Durham",
    "Jersey City",
    "Chandler",
    "Chula Vista",
    "Buffalo",
    "North Las Vegas",
    "Gilbert",
    "Madison",
    "Reno",
    "Toledo",
    "Fort Wayne",
    "Lubbock",
    "St. Petersburg",
    "Laredo",
    "Irving",
    "Chesapeake",
    "Winston–Salem",
    "Glendale",
    "Scottsdale",
    "Garland",
    "Boise",
    "Norfolk",
    "Spokane",
    "Fremont",
    "Richmond",
    "Santa Clarita",
    "San Bernardino",
    "Baton Rouge",
    "Hialeah",
    "Tacoma",
    "Modesto",
    "Port St. Lucie",
    "Huntsville",
    "Des Moines",
    "Moreno Valley",
    "Fontana",
    "Frisco",
    "Rochester",
    "Yonkers",
    "Fayetteville",
    "Worcester",
    "Columbus",
    "Cape Coral",
    "McKinney",
    "Little Rock",
    "Oxnard",
    "Amarillo",
    "Augusta",
    "Salt Lake City",
    "Montgomery",
    "Birmingham",
    "Grand Rapids",
    "Grand Prairie",
    "Overland Park",
    "Tallahassee",
    "Huntington Beach",
    "Sioux Falls",
    "Peoria",
    "Knoxville",
    "Glendale",
    "Vancouver WA",
    "Providence",
    "Akron",
    "Brownsville",
    "Mobile",
    "Newport News",
    "Tempe",
    "Shreveport",
    "Chattanooga",
    "Fort Lauderdale",
    /*Canada*/
    "Toronto",
    "Edmonton",
    "Ottawa",
    "Victoria",
    "Vancouver",
    "Montreal",
    "Winnipeg",
    "Fredericton",
    "St. John's",
    "Halifax",
    "Charlottetown",
    "Quebec City",
    "Regina",
    "Yellowknife",
    "Iqaluit",
    "Whitehorse",
    /*Australia*/
    "Adelaide",
    "Albany",
    "Alice Springs",
    "Armidale",
    "Aurukun",
    "Balladonia",
    "Ballarat",
    "Bamaga",
    "Barcaldine",
    "Barkly Homestead",
    "Bathurst",
    "Bendigo",
    "Biloela",
    "Boulia",
    "Bourke",
    "Brisbane",
    "Broken Hill",
    "Broome",
    "Bunbury",
    "Bundaberg",
    "Cairns",
    "Canberra",
    "Carnarvon",
    "Ceduna",
    "Central Coast",
    "Charleville",
    "Clermont",
    "Cloncurry",
    "Coffs Harbour",
    "Coober Pedy",
    "Cunnamulla",
    "Dalby",
    "Darwin",
    "Derby",
    "Devonport",
    "Doomadgee",
    "Dubbo",
    "Elliott",
    "Emerald",
    "Esperance",
    "Exmouth",
    "Geelong",
    "Geraldton",
    "Gladstone",
    "Gold Coast",
    "Goondiwindi",
    "Goulburn",
    "Hervey Bay",
    "Hobart",
    "Hughenden",
    "Kalgoorlie-Boulder",
    "Kalumburu",
    "Karratha",
    "Katherine",
    "Kowanyama",
    "Kulgera",
    "Kununurra",
    "La Grange",
    "Launceston",
    "Leonora",
    "Lismore",
    "Lombadina",
    "Mackay",
    "Mandurah",
    "Marree",
    "Maryborough",
    "Meekatharra",
    "Melbourne",
    "Mildura",
    "Miles",
    "Mount Gambier",
    "Mount Isa",
    "Newcastle",
    "Newman",
    "Nguiu",
    "Normanton",
    "Norseman",
    "Northam",
    "Nowra",
    "Nyngan",
    "Onslow",
    "Orange",
    "Perth",
    "Peterborough",
    "Pine Creek",
    "Port Hedland,",
    "Port Lincoln",
    "Port Macquarie",
    "Queanbeyan",
    "Queenstown",
    "Quilpie",
    "Renmark",
    "Rockhampton",
    "Rockingham",
    "Shepparton",
    "Southern Cross",
    "Sunshine Coast",
    "Sydney",
    "Tamworth",
    "Tarcoola",
    "Tennant Creek",
    "Thargomindah",
    "Toowoomba",
    "Townsville",
    "Tweed Heads",
    "Wagga Wagga",
    "Warrnambool",
    "Weipa,",
    "Whyalla",
    "Wilcannia",
    "Winton",
    "Wollongong",
    "Wyndham",
    "Yarrie",
    "Yulara",
    /*Spain*/
    "Madrid",
    "Barcelona",
    "Seville",
    "Bilbao",
    "Valencia",
    "Málaga",
    "Oviedo–Gijón–Avilés",
    "Alicante–Elche",
    "Las Palmas",
    "Zaragoza",
    "Murcia–Orihuela",
    "Santa Cruz de Tenerife–La Laguna",
    "Granada",
    "Palma",
    "Vigo",
    "Cartagena",
    "Cádiz",
    "San Sebastián",
    "A Coruña–Oleiros–Arteixo",
    "Valladolid",
    "Tarragona",
    "Córdoba",
    "Pamplona",
    "Castellón de la Plana",
    "Santander–Torrelavega",
    "Alzira–Xàtiva",
    "Vitoria-Gasteiz",
    "Algeciras–La Línea",
    "Huelva",
    "Almería",
    "Salamanca",
    "Jerez de la Frontera",
    "León",
    "Albacete",
    "Jaén–Martos",
    "Burgos",
    "Logroño",
    "Ferrol–Narón",
    "Lleida",
    "Girona–Salt",
    "Pontevedra–Marín",
    /* Italy*/
    "Rome",
    "Milan",
    "Naples",
    "Turin",
    /*Belgium*/
    "Brussels",
    "Antwerp",
    "Ghent",
    "Charleroi",
    "Condamine",
    /*Monte Carlo*/
    "Monte Carlo",
    "Moneghetti",
    "Monaco-Ville",
    /*UK*/
    "London",
    "Manchester",
    "Birmingham",
    "Leeds",
    /*France*/
    "Paris",
    "Marseille",
    "Lyon",
    "Toulouse",
    "Nice",
    "Nantes",
    "Montpellier",
    "Strasbourg",
    /*Germany*/
    "Berlin",
    "Hamburg",
    "München",
    "Köln",
    "Frankfurt",
    "Stuttgart",
    "Düsseldorf",
    "Dortmund",
    /*Netherlands*/
    "Amsterdam",
    "Rotterdam",
    "Hague",
    "Utrecht",
    "Eindhoven",
    "Tilburg",
    "Groningen",
    "Almere",
    /* UAE*/
    "Abu Dhabi",
    "Dubai",
    "Sharjah",
    "Ajman",
    /*KSA*/
    "Riyad",
    "Jeddah",
    "Mekkah",
    "Madina",
    "Khubar",
    "Damam",
    /*Egypt*/
    "Cairo",
    "Alxandria",
    "Jezzah",
    "Esmailya",
    "Suez",
    "Aswan",
    "Marsa",
    "Porsaed",
    /*Kuwait*/
    "Asima",
    "Jahra",
    "Salmiya",
    "Hawali",
    /*Oman*/
    "Muscat",
    "Salalah",
    /*Turkey*/
    "Ankara",
    "Istanbul",
    "Izmer",
    "Samsun",
    /*Iraq*/
    "Baghdad",
    "Basrah",
    "Mosul",
    "Arbel",
    /*Qatar*/
    "Doha",
    /*Malaysia*/
    "Kuala Lumpur",
    "Selangore",
    "Johor",
    "Penang",
    /*Japan*/
    "Sapporo",
    "Tokyo",
    "Yokohama",
    "Nagoya",
    "Kyoto",
    "Nara",
    "Osaka",
    "Kobe",
    /*Korea*/
    "Seoul",
    "Busan",
    "Incheon",
    "Daegu",
    "Daejeon",
    "Gwangju",
    "Suwon",
    "Goyang-s",
    /*India*/
    "Mumbai",
    "Delhi",
    "Bangalore",
    "Hyderabad",
    "Ahmedabad",
    "Chennai",
    "Kolkata",
    "Surat",
    /*Algeria*/
    "Algiers",
    "Annaba",
    "Azazga",
    "Batna City",
    "Blida",
    "Bordj",
    "Bordj Bou Arreridj",
    "Bougara",
    "Cheraga",
    "Chlef",
    "Constantine",
    "Djelfa",
    "Draria",
    "El Tarf",
    "Hussein Dey",
    "Illizi",
    "Jijel",
    "Kouba",
    "Laghouat",
    "Oran",
    "Ouargla",
    "Oued Smar",
    "Relizane",
    "Rouiba",
    "Saida",
    "Souk Ahras",
    "Tamanghasset",
    "Tiaret",
    "Tissemsilt",
    "Tizi",
    "Tizi Ouzou",
    "Tlemcen",
    /*---*/
    'Afghanistan',
    'Albania',
    'Algeria',
    'American Samoa',
    'Andorra',
    'Angola',
    'Anguilla',
    'Antarctica',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia',
    'Aruba',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bermuda',
    'Bhutan',
    'Bolivia',
    'Bosnia and Herzegovina',
    'Botswana',
    'Bouvet Island',
    'Brazil',
    'British Antarctic Territory',
    'British Indian Ocean Territory',
    'British Virgin Islands',
    'Brunei',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Canton and Enderbury Islands',
    'Cape Verde',
    'Cayman Islands',
    'Central African Republic',
    'Chad',
    'Chile',
    'China',
    'Christmas Island',
    'Cocos [Keeling] Islands',
    'Colombia',
    'Comoros',
    'Congo - Brazzaville',
    'Congo - Kinshasa',
    'Cook Islands',
    'Costa Rica',
    'Croatia',
    'Cuba',
    'Cyprus',
    'Czech Republic',
    'Côte d’Ivoire',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'Dronning Maud Land',
    'East Germany',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Ethiopia',
    'Falkland Islands',
    'Faroe Islands',
    'Fiji',
    'Finland',
    'France',
    'French Guiana',
    'French Polynesia',
    'French Southern Territories',
    'French Southern and Antarctic Territories',
    'Gabon',
    'Gambia',
    'Georgia',
    'Germany',
    'Ghana',
    'Gibraltar',
    'Greece',
    'Greenland',
    'Grenada',
    'Guadeloupe',
    'Guam',
    'Guatemala',
    'Guernsey',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Heard Island and McDonald Islands',
    'Honduras',
    'Hong Kong SAR China',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    "Iraq",
    'Ireland',
    'Isle of Man',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jersey',
    'Johnston Island',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Macau SAR China',
    'Macedonia',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands',
    'Martinique',
    'Mauritania',
    'Mauritius',
    'Mayotte',
    'Metropolitan France',
    'Mexico',
    'Micronesia',
    'Midway Islands',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Montserrat',
    'Morocco',
    'Mozambique',
    'Myanmar [Burma]',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherlands',
    'Netherlands Antilles',
    'Neutral Zone',
    'New Caledonia',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'Niue',
    'Norfolk Island',
    'North Korea',
    'North Vietnam',
    'Northern Mariana Islands',
    'Norway',
    'Oman',
    'Pacific Islands Trust Territory',
    'Pakistan',
    'Palau',
    'Palestinian Territories',
    'Panama',
    'Panama Canal Zone',
    'Papua New Guinea',
    'Paraguay',
    'Yemen',
    'Peru',
    'Philippines',
    'Pitcairn Islands',
    'Poland',
    'Portugal',
    'Puerto Rico',
    'Qatar',
    'Romania',
    'Russia',
    'Rwanda',
    'Réunion',
    'Saint Barthélemy',
    'Saint Helena',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Martin',
    'Saint Pierre and Miquelon',
    'Saint Vincent and the Grenadines',
    'Samoa',
    'San Marino',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Serbia and Montenegro',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'South Georgia and the South Sandwich Islands',
    'South Korea',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Svalbard and Jan Mayen',
    'Swaziland',
    'Sweden',
    'Switzerland',
    'Syria',
    'São Tomé and Príncipe',
    'Taiwan',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'Timor-Leste',
    'Togo',
    'Tokelau',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Turks and Caicos Islands',
    'Tuvalu',
    'U.S. Minor Outlying Islands',
    'U.S. Miscellaneous Pacific Islands',
    'U.S. Virgin Islands',
    'Uganda',
    'Ukraine',
    'Russia',
    'United Arab Emirates',
    'United Kingdom',
    'United States',
    'Unknown or Invalid Region',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Vatican City',
    'Venezuela',
    'Vietnam',
    'Wake Island',
    'Wallis and Futuna',
    'Western Sahara',
    'Yemen',
    'Zambia',
    'Zimbabwe',
    'Åland Islands',
  ];
  static List<String> countries = [
    'Afghanistan',
    'Albania',
    'Algeria',
    'American Samoa',
    'Andorra',
    'Angola',
    'Anguilla',
    'Antarctica',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia',
    'Aruba',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bermuda',
    'Bhutan',
    'Bolivia',
    'Bosnia and Herzegovina',
    'Botswana',
    'Bouvet Island',
    'Brazil',
    'British Antarctic Territory',
    'British Indian Ocean Territory',
    'British Virgin Islands',
    'Brunei',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Canton and Enderbury Islands',
    'Cape Verde',
    'Cayman Islands',
    'Central African Republic',
    'Chad',
    'Chile',
    'China',
    'Christmas Island',
    'Cocos [Keeling] Islands',
    'Colombia',
    'Comoros',
    'Congo - Brazzaville',
    'Congo - Kinshasa',
    'Cook Islands',
    'Costa Rica',
    'Croatia',
    'Cuba',
    'Cyprus',
    'Czech Republic',
    'Côte d’Ivoire',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'Dronning Maud Land',
    'East Germany',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Ethiopia',
    'Falkland Islands',
    'Faroe Islands',
    'Fiji',
    'Finland',
    'France',
    'French Guiana',
    'French Polynesia',
    'French Southern Territories',
    'French Southern and Antarctic Territories',
    'Gabon',
    'Gambia',
    'Georgia',
    'Germany',
    'Ghana',
    'Gibraltar',
    'Greece',
    'Greenland',
    'Grenada',
    'Guadeloupe',
    'Guam',
    'Guatemala',
    'Guernsey',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Heard Island and McDonald Islands',
    'Honduras',
    'Hong Kong SAR China',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    "Iraq",
    'Ireland',
    'Isle of Man',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jersey',
    'Johnston Island',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Macau SAR China',
    'Macedonia',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands',
    'Martinique',
    'Mauritania',
    'Mauritius',
    'Mayotte',
    'Metropolitan France',
    'Mexico',
    'Micronesia',
    'Midway Islands',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Montserrat',
    'Morocco',
    'Mozambique',
    'Myanmar [Burma]',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherlands',
    'Netherlands Antilles',
    'Neutral Zone',
    'New Caledonia',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'Niue',
    'Norfolk Island',
    'North Korea',
    'North Vietnam',
    'Northern Mariana Islands',
    'Norway',
    'Oman',
    'Pacific Islands Trust Territory',
    'Pakistan',
    'Palau',
    'Palestinian Territories',
    'Panama',
    'Panama Canal Zone',
    'Papua New Guinea',
    'Paraguay',
    'Yemen',
    'Peru',
    'Philippines',
    'Pitcairn Islands',
    'Poland',
    'Portugal',
    'Puerto Rico',
    'Qatar',
    'Romania',
    'Russia',
    'Rwanda',
    'Réunion',
    'Saint Barthélemy',
    'Saint Helena',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Martin',
    'Saint Pierre and Miquelon',
    'Saint Vincent and the Grenadines',
    'Samoa',
    'San Marino',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Serbia and Montenegro',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'South Georgia and the South Sandwich Islands',
    'South Korea',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Svalbard and Jan Mayen',
    'Swaziland',
    'Sweden',
    'Switzerland',
    'Syria',
    'São Tomé and Príncipe',
    'Taiwan',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'Timor-Leste',
    'Togo',
    'Tokelau',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Turks and Caicos Islands',
    'Tuvalu',
    'U.S. Minor Outlying Islands',
    'U.S. Miscellaneous Pacific Islands',
    'U.S. Virgin Islands',
    'Uganda',
    'Ukraine',
    'Russia',
    'United Arab Emirates',
    'United Kingdom',
    'United States',
    'Unknown or Invalid Region',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Vatican City',
    'Venezuela',
    'Vietnam',
    'Wake Island',
    'Wallis and Futuna',
    'Western Sahara',
    'Yemen',
    'Zambia',
    'Zimbabwe',
    'Åland Islands',
  ];
  static List<String> citiess = [
    "Herat",
    "Kabul",
    "Kandahar",
    "Molah",
    "Rana",
    "Shar",
    "Sharif",
    "Wazir Akbar Khan",
    "Elbasan",
    "Petran",
    "Pogradec",
    "Shkoder",
    "Tirana",
    "Ura Vajgurore",
    "Andorra la Vella",
    "Canillo",
    "Encamp",
    "Engordany",
    "Escaldes-Engordany",
    "La Massana",
    "Llorts",
    "Ordino",
    "Santa Coloma",
    "Sispony",
    "Soldeu",
    "Ambriz",
    "Benguela",
    "Cabinda",
    "Cacole",
    "Camabatela",
    "Cazeta",
    "Huambo",
    "Kuito",
    "Lobito",
    "Luanda",
    "Lubango",
    "Lucapa",
    "Lumeje",
    "Malanje",
    "Menongue",
    "Muxaluando",
    "Namibe",
    "Ondjiva",
    "Piri",
    "Saurimo",
    "Talatona",
    "All Saints",
    "Cassada Gardens",
    "Codrington",
    "Old Road",
    "Parham",
    "Woods",
    "28 de Noviembre",
    "Abasto",
    "Acassuso",
    "Acebal",
    "Acevedo",
    "Adelia Maria",
    "Agua de Oro",
    "Albardon",
    "Albarellos",
    "Alberdi",
    "Alberti",
    "Aldo Bonzi",
    "Alejandro Korn",
    "Alicia",
    "Allen",
    "Almafuerte",
    "Almagro",
    "Almirante Brown",
    "Alta Gracia",
    "Alta Italia",
    "Alvarez",
    "Alvear",
    "Anatuya",
    "Angelica",
    "Antonio Carboni",
    "Apostoles",
    "Arequito",
    "Armstrong",
    "Arrecifes",
    "Arroyito",
    "Arroyito",
    "Arroyito Challaco",
    "Arroyo Seco",
    "Arteaga",
    "Asamblea",
    "Ascension",
    "Avellaneda",
    "Avellaneda",
    "Ayacucho",
    "Azara",
    "Azul",
    "Balcarce",
    "Balnearia",
    "Banda del Rio Sali",
    "Bandera",
    "Banfield",
    "Baradero",
    "Bariloche",
    "Barrio Fisherton",
    "Batan",
    "Beccar",
    "Belen de Escobar",
    "Belgrano",
    "Belgrano",
    "Bell Ville",
    "Bella Vista",
    "Bella Vista",
    "Benavidez",
    "Berazategui",
    "Berisso",
    "Bernal",
    "Bernardo Larroude",
    "Bernasconi",
    "Bigand",
    "Bombal",
    "Bordenave",
    "Bosch",
    "Bosques",
    "Boulogne",
    "Bovril",
    "Bragado",
    "Brandsen",
    "Brinkmann",
    "Buenos Aires",
    "Burzaco",
    "Bustinza",
    "Caballito",
    "Calderon",
    "Caleta Olivia",
    "Caleufu",
    "Camilo Aldao",
    "Campana",
    "Canada de Gomez",
    "Canada del Ucle",
    "Canada Rosquin",
    "Canals",
    "Canning",
    "Canuelas",
    "Capilla del Monte",
    "Capilla del Senor",
    "Capitan Bermudez",
    "Carhue",
    "Carlos Casares",
    "Carlos Pellegrini",
    "Carlos Tejedor",
    "Caseros",
    "Casilda",
    "Castelar",
    "Castelli",
    "Castillo",
    "Catriel",
    "Catrilo",
    "Cavanagh",
    "Centenario",
    "Ceres",
    "Cervantes",
    "Chacabuco",
    "Chacarita",
    "Chajari",
    "Charata",
    "Chateaubriand",
    "Chilecito",
    "Chivilcoy",
    "Choele Choel",
    "Chorroarin",
    "Cinco Saltos",
    "Cipolletti",
    "City Bell",
    "Ciudad General Belgrano",
    "Ciudadela",
    "Claypole",
    "Clorinda",
    "Colon",
    "Colon",
    "Colonia Baron",
    "Colonia Caroya",
    "Colonia San Miguel Arcangel",
    "Comodoro Rivadavia",
    "Concepcion",
    "Concepcion",
    "Concordia",
    "Constituyentes",
    "Coronel Dorrego",
    "Coronel Martinez de Hoz",
    "Coronel Pringles",
    "Corral de Bustos",
    "Corralitos",
    "Corrientes",
    "Cosquin",
    "Coy Aike",
    "Cramer",
    "Crespo",
    "Cruz del Eje",
    "Curuzu Cuatia",
    "Cutral-Co",
    "Darregueira",
    "De Mayo",
    "Del Campillo",
    "Del Viso",
    "Despenaderos",
    "Devoto",
    "Diaz",
    "Diego de Alvear",
    "Doblas",
    "Dock Sud",
    "Dolores",
    "Don Bosco",
    "Don Torcuato",
    "Drabble",
    "Eduardo Castex",
    "El Calafate",
    "El Dorado",
    "El Hoyo",
    "El Palomar",
    "El Palomar",
    "El Talar",
    "El Trebol",
    "Eldorado",
    "Embalse",
    "Empalme Lobos",
    "Ensenada",
    "Esperanza",
    "Esquel",
    "Esteban Echeverria",
    "Ezeiza",
    "Ezpeleta",
    "Famailla",
    "Fatima",
    "Federal",
    "Fernandez",
    "Firmat",
    "Florencio Varela",
    "Florentino Ameghino",
    "Flores",
    "Floresta",
    "Florida",
    "Formosa",
    "Francisco Alvarez",
    "Franck",
    "Fray Luis A. Beltran",
    "Freyre",
    "Frias",
    "Funes",
    "Gaiman",
    "Galvez",
    "Garin",
    "Garupa",
    "General Acha",
    "General Alvear",
    "General Cabrera",
    "General Deheza",
    "General Guido",
    "General Juan Madariaga",
    "General Lagos",
    "General Las Heras",
    "General Lavalle",
    "General Mansilla",
    "General Martin Miguel de Guemes",
    "General Pacheco",
    "General Paz",
    "General Pico",
    "General Roca",
    "General Roca",
    "General Rodriguez",
    "General San Martin",
    "General San Martin",
    "General Viamonte",
    "General Villegas",
    "Germania",
    "Glew",
    "Gobernador Crespo",
    "Gobernador Galvez",
    "Godoy",
    "Godoy Cruz",
    "Gonzalez Catan",
    "Gonzalez Moreno",
    "Goya",
    "Granadero Baigorria",
    "Grand Bourg",
    "Gualeguay",
    "Guatrache",
    "Guernica",
    "Henderson",
    "Hernando",
    "Hersilia",
    "Hilario",
    "Hilario Ascasubi",
    "Hipatia",
    "Hipolito Yrigoyen",
    "Huanchillas",
    "Huanguelen",
    "Huinca Renanco",
    "Humahuaca",
    "Hurlingham",
    "Ibarlucea",
    "Ibicuy",
    "Independencia",
    "Ingeniero Beaugey",
    "Ingeniero Luiggi",
    "Ingeniero Maschwitz",
    "Intendente Alvear",
    "Isidro Casanova",
    "Ituzaingo",
    "James Craik",
    "Jauregui",
    "Jeppener",
    "Jesus Maria",
    "Jose Leon Suarez",
    "Jose Marmol",
    "Juan Pujol",
    "Justiniano Posse",
    "La Banda",
    "La Boca",
    "La Calera",
    "La Cumbre",
    "La Falda",
    "La Leonesa",
    "La Lucila",
    "La Madrid",
    "La Pampa",
    "La Para",
    "La Paz",
    "La Paz",
    "La Plata",
    "La Punta",
    "La Rioja",
    "La Tablada",
    "La Union",
    "La Violeta",
    "Laborde",
    "Laboulaye",
    "Laferrere",
    "Laguna Alsina",
    "Lanus",
    "Larroque",
    "Las Catitas",
    "Las Flores",
    "Las Flores",
    "Las Heras",
    "Las Perdices",
    "Las Rosas",
    "Las Talitas",
    "Las Varillas",
    "Lavalle",
    "Leandro N. Alem",
    "Leones",
    "Libertad",
    "Lima",
    "Liniers",
    "Llavallol",
    "Lobos",
    "Lomas de Zamora",
    "Lomas del Mirador",
    "Longchamps",
    "Los Antiguos",
    "Los Cardales",
    "Los Molinos",
    "Los Polvorines",
    "Luis Guillon",
    "Lujan de Cuyo",
    "Luque",
    "Luzuriaga",
    "Lynch",
    "Macachin",
    "Magdalena",
    "Magdalena",
    "Maggiolo",
    "Maipu",
    "Maipu",
    "Manantial",
    "Manfredi",
    "Manuel J. Cobo",
    "Maquinista Savio",
    "Mar de Ajo",
    "Mar del Plata",
    "Mar del Tuyu",
    "Marcos Juarez",
    "Marcos Paz",
    "Margarita",
    "Maria Ignacia",
    "Maria Juana",
    "Mariano Acosta",
    "Mariano J. Haedo",
    "Mariano Moreno",
    "Martinez",
    "Matheu",
    "Mayor Buratovich",
    "Melincue",
    "Mendiolaza",
    "Mendoza",
    "Mercedes",
    "Mercedes",
    "Merlo",
    "Merlo",
    "Minacar",
    "Miramar",
    "Miramar",
    "Monje",
    "Monte Hermoso",
    "Monteros",
    "Montserrat",
    "Moreno",
    "Moron",
    "Morteros",
    "Muniz",
    "Munro",
    "Navarro",
    "Navarro",
    "Necochea",
    "Nogoya",
    "Nordelta",
    "Nunez",
    "Obera",
    "Oliva",
    "Oliveros",
    "Olivos",
    "Oncativo",
    "Open Door",
    "Ordonez",
    "Palermo",
    "Palmira",
    "Palpala",
    "Partido de Jose C. Paz",
    "Pasco",
    "Paso del Rey",
    "Paternal",
    "Pavon",
    "Pedernales",
    "Pedro Luro",
    "Pellegrini",
    "Perez",
    "Pergamino",
    "Perico",
    "Perito Moreno",
    "Piamonte",
    "Pico de Salamanca",
    "Pico Truncado",
    "Pigue",
    "Pilar",
    "Pilar",
    "Pilar",
    "Pinamar",
    "Piquete Cabado",
    "Platanos",
    "Plaza Huincul",
    "Plottier",
    "Pontevedra",
    "Portena",
    "Posadas",
    "Pozo del Molle",
    "Presidente Derqui",
    "Puan",
    "Pueblo San Jose",
    "Puerto Madryn",
    "Puerto Rico",
    "Pueyrredon",
    "Punta Alta",
    "Quilmes",
    "Rada Tilly",
    "Rafael Calzada",
    "Rafael Castillo",
    "Rafael Obligado",
    "Rafaela",
    "Ramallo",
    "Ramos Mejia",
    "Ranchos",
    "Rancul",
    "Ranelagh",
    "Rawson",
    "Rawson",
    "Realico",
    "Recoleta",
    "Reconquista",
    "Remedios de Escalada",
    "Resistencia",
    "Retiro",
    "Rio Ceballos",
    "Rio Colorado",
    "Rio Grande",
    "Rio Piedras",
    "Rio Segundo",
    "Rio Tercero",
    "Rivadavia",
    "Rivadavia",
    "Rivadavia",
    "Rocamora",
    "Rodriguez Pena",
    "Rojas",
    "Roldan",
    "Roque Perez",
    "Rosario",
    "Rosas",
    "Rufino",
    "Sacanta",
    "Saenz Pena",
    "Saladillo",
    "Saladillo",
    "Salguero",
    "Salsipuedes",
    "Salta",
    "Salto",
    "Salto Grande",
    "Sampacho",
    "San Andres",
    "San Andres de Giles",
    "San Antonio de Areco",
    "San Antonio de Arredondo",
    "San Antonio de Obligado",
    "San Antonio de Padua",
    "San Antonio Oeste",
    "San Benito",
    "San Bernardo",
    "San Carlos de Bolivar",
    "San Cayetano",
    "San Clemente",
    "San Cristobal",
    "San Fernando",
    "San Fernando del Valle de Catamarca",
    "San Francisco",
    "San Francisco de Santa Fe",
    "San Francisco Solano",
    "San Genaro",
    "San Gregorio",
    "San Guillermo",
    "San Isidro",
    "San Isidro",
    "San Isidro de Lules",
    "San Javier",
    "San Jeronimo Norte",
    "San Jorge",
    "San Jose",
    "San Jose de la Esquina",
    "San Juan",
    "San Justo",
    "San Lorenzo",
    "San Luis",
    "San Manuel",
    "San Martin",
    "San Martin de las Escobas",
    "San Miguel",
    "San Miguel",
    "San Miguel",
    "San Miguel del Monte",
    "San Nicolas",
    "San Pedro",
    "San Pedro",
    "San Rafael",
    "San Salvador",
    "San Salvador",
    "San Salvador de Jujuy",
    "San Telmo",
    "San Vicente",
    "Sanchez",
    "Santa Clara de Saguier",
    "Santa Elena",
    "Santa Fe",
    "Santa Lucia",
    "Santa Lucia",
    "Santa Rita",
    "Santa Rosa",
    "Santa Teresita",
    "Santiago del Estero",
    "Santo Tome",
    "Santos Lugares",
    "Sarandi",
    "Sarmiento",
    "Sarmiento",
    "Segui",
    "Sierra de la Ventana",
    "Sierra de los Padres",
    "Sinsacate",
    "Suipacha",
    "Sunchales",
    "Tablada",
    "Tacuari",
    "Tafi Viejo",
    "Tandil",
    "Tapalque",
    "Tapiales",
    "Temperley",
    "Teodelina",
    "Thames",
    "Tigre",
    "Tio Pujio",
    "Todd",
    "Tornquist",
    "Tortuguitas",
    "Tostado",
    "Totoras",
    "Trelew",
    "Trenque Lauquen",
    "Tres Arroyos",
    "Trevelin",
    "Tristan Suarez",
    "Tunuyan",
    "Tupungato",
    "Turdera",
    "Ucacha",
    "Uriburu",
    "Ushuaia",
    "Valle Hermoso",
    "Vedia",
    "Veinticinco de Mayo",
    "Veinticinco de Mayo",
    "Venado Tuerto",
    "Vera",
    "Veronica",
    "Viale",
    "Viamonte",
    "Vicente Lopez",
    "Victoria",
    "Victoria",
    "Vicuna Mackenna",
    "Viedma",
    "Villa Aberastain",
    "Villa Adelina",
    "Villa Allende",
    "Villa Alsina",
    "Villa Amelia",
    "Villa Angela",
    "Villa Ballester",
    "Villa Bosch",
    "Villa Canas",
    "Villa Carlos Paz",
    "Villa Constitucion",
    "Villa de Maria",
    "Villa de Mayo",
    "Villa del Parque",
    "Villa Dolores",
    "Villa Dominico",
    "Villa Elisa",
    "Villa General Belgrano",
    "Villa Gesell",
    "Villa Giardino",
    "Villa Huidobro",
    "Villa Insuperable",
    "Villa La Angostura",
    "Villa Las Rosas",
    "Villa Lugano",
    "Villa Luzuriaga",
    "Villa Madero",
    "Villa Maria Grande",
    "Villa Media Agua",
    "Villa Mercedes",
    "Villa Mercedes",
    "Villa Nueva",
    "Villa Nueva",
    "Villa Ocampo",
    "Villa Paranacito",
    "Villa Regina",
    "Villa Robles",
    "Villa Rosa",
    "Villa Trinidad",
    "Villa Urquiza",
    "Villaguay",
    "Vuelta de Obligado",
    "Warnes",
    "Wheelwright",
    "Wilde",
    "Winifreda",
    "Yerba Buena",
    "Zenon Pereyra",
    "Abovyan",
    "Agarak",
    "Apaga",
    "Aparan",
    "Arabkir",
    "Ashtarak",
    "Erebuni Fortress",
    "Hrazdan",
    "Ijevan",
    "Jermuk",
    "Kapan",
    "Tsaghkadzor",
    "Vanadzor",
    "Yerevan",
    "Noord",
    "Oranjestad",
    "Palm Beach",
    "Paradera",
    "Ponton",
    "Sabaneta",
    "San Barbola",
    "Santa Cruz",
    "Sero Blanco",
    "Sint Nicolaas",
    "Tanki Lender",
    "Abbotsford",
    "Abbotsford",
    "Abbotsham",
    "Aberdeen",
    "Aberfoyle",
    "Aberglasslyn",
    "Abermain",
    "Acacia Ridge",
    "Adamstown",
    "Adelaide",
    "Adelong",
    "Advancetown",
    "Agnes Banks",
    "Agnes Water",
    "Airlie Beach",
    "Aitkenvale",
    "Albany",
    "Albany Creek",
    "Albert Park",
    "Alberton",
    "Alberton",
    "Albion",
    "Albion Park",
    "Albury",
    "Aldgate",
    "Aldinga",
    "Aldinga Beach",
    "Alexandra",
    "Alexandra",
    "Alexandria",
    "Alfredton",
    "Alice Springs",
    "Allambee",
    "Allansford",
    "Allanson",
    "Allora",
    "Alma",
    "Alphington",
    "Alpine",
    "Alstonville",
    "Alton Downs",
    "Altona",
    "Amamoor",
    "Amaroo",
    "Angaston",
    "Anglesea",
    "Anna Bay",
    "Annandale",
    "Apollo Bay",
    "Applecross",
    "Applethorpe",
    "Ararat",
    "Arcadia",
    "Argents Hill",
    "Armadale",
    "Armadale",
    "Armidale",
    "Armstrong Creek",
    "Arno Bay",
    "Arrawarra",
    "Artarmon",
    "Ascot",
    "Ascot Vale",
    "Ashburton",
    "Ashfield",
    "Ashgrove",
    "Ashton",
    "Aspendale",
    "Aspley",
    "Asquith",
    "Atherton",
    "Attadale",
    "Auburn",
    "Augusta",
    "Austinmer",
    "Austins Ferry",
    "Australind",
    "Avalon",
    "Avenue",
    "Avoca Beach",
    "Avondale",
    "Axedale",
    "Aylmerton",
    "Ayr",
    "Babinda",
    "Bacchus Marsh",
    "Bagdad",
    "Bahrs Scrub",
    "Bairnsdale",
    "Baker",
    "Balaclava",
    "Balaklava",
    "Bald Hills",
    "Balgowlah",
    "Balgownie",
    "Balhannah",
    "Ballan",
    "Ballarat",
    "Ballina",
    "Balmain",
    "Balmoral",
    "Balnarring",
    "Balwyn",
    "Balwyn North",
    "Bangalow",
    "Bangor",
    "Banksmeadow",
    "Bankstown",
    "Bannockburn",
    "Barcoo",
    "Barellan",
    "Bargara",
    "Bargo",
    "Baringhup",
    "Barkstead",
    "Barnsley",
    "Barry",
    "Barwon Downs",
    "Barwon Heads",
    "Barwon Heads",
    "Basin View",
    "Bass Hill",
    "Bassendean",
    "Batchelor",
    "Bateau Bay",
    "Batesford",
    "Bathurst",
    "Batlow",
    "Baulkham Hills",
    "Baxter",
    "Bayles",
    "Baynton",
    "Bayswater",
    "Beachmere",
    "Beacon",
    "Beaconsfield",
    "Beaconsfield Upper",
    "Beaudesert",
    "Beaumaris",
    "Beaumont",
    "Beaumont",
    "Beauty Point",
    "Bedford Park",
    "Bedfordale",
    "Beeac",
    "Beechwood",
    "Beechworth",
    "Beenak",
    "Beenleigh",
    "Beerwah",
    "Bega",
    "Belair",
    "Belconnen",
    "Belgian Gardens",
    "Belgrave",
    "Belgrave Heights",
    "Bell",
    "Bellambi",
    "Bellara",
    "Bellbird",
    "Bellbrae",
    "Bellerive",
    "Bellevue Hill",
    "Belmont",
    "Belmont",
    "Belmont",
    "Belrose",
    "Benalla",
    "Benambra",
    "Bendigo",
    "Benowa",
    "Bensville",
    "Bentleigh",
    "Bentleigh East",
    "Bentley",
    "Bentley",
    "Beresfield",
    "Berkeley",
    "Berkeley Vale",
    "Berowra",
    "Berridale",
    "Berrima",
    "Berry",
    "Berwick",
    "Bethania Junction",
    "Beveridge",
    "Beverley",
    "Beverley",
    "Bexley",
    "Bicheno",
    "Bicton",
    "Big Pats Creek",
    "Bilinga",
    "Biloela",
    "Bilpin",
    "Binda",
    "Binnaway",
    "Birdwood",
    "Birkdale",
    "Birkenhead",
    "Black Hill",
    "Black Rock",
    "Blackburn",
    "Blackbutt",
    "Blackheath",
    "Blackmans Bay",
    "Blacktown",
    "Blackwall",
    "Blackwarry",
    "Blackwater",
    "Blackwood",
    "Blackwood",
    "Blair Athol",
    "Blair Athol",
    "Blakehurst",
    "Blaxland",
    "Blayney",
    "Bli Bli",
    "Boambee",
    "Boat Harbour",
    "Bobin",
    "Boddington",
    "Bogangar",
    "Bohle Plains",
    "Bolton",
    "Bolwarra",
    "Bomaderry",
    "Bombala",
    "Bonbeach",
    "Bondi",
    "Boneo",
    "Bongaree",
    "Bonnells Bay",
    "Bonnet Bay",
    "Bonython",
    "Booker Bay",
    "Bool Lagoon",
    "Boolarra",
    "Boonah",
    "Boondall",
    "Booral",
    "Bordertown",
    "Boronia",
    "Botany",
    "Boulder",
    "Bourke",
    "Bowen",
    "Bowenfels",
    "Bowral",
    "Bowraville",
    "Box Hill",
    "Box Hill South",
    "Boyup Brook",
    "Bradbury",
    "Braddon",
    "Braeside",
    "Braidwood",
    "Brandon",
    "Brandy Hill",
    "Branxton",
    "Brewarrina",
    "Briar Hill",
    "Bridgetown",
    "Bridgewater",
    "Bridgewater",
    "Brighton",
    "Brighton",
    "Brighton",
    "Brighton East",
    "Brighton-Le-Sands",
    "Bringelly",
    "Brisbane",
    "Broadbeach",
    "Broadford",
    "Broadmeadows",
    "Broadwater",
    "Broadwater",
    "Broke",
    "Broken Hill",
    "Bronte",
    "Brookdale",
    "Brookfield",
    "Brookfield",
    "Brooklyn",
    "Brookvale",
    "Broome",
    "Brown Hill",
    "Browns Plains",
    "Bruce",
    "Brunswick",
    "Buchan",
    "Buckland",
    "Buderim",
    "Budgewoi",
    "Bulahdelah",
    "Bulga",
    "Bulimba",
    "Bulla",
    "Bulleen",
    "Bulli",
    "Bullsbrook",
    "Bullyard",
    "Buln Buln",
    "Bunbury",
    "Bundaberg",
    "Bundalong",
    "Bundamba",
    "Bundanoon",
    "Bundeena",
    "Bundook",
    "Bundoora",
    "Bungendore",
    "Bungonia",
    "Buninyong",
    "Burekup",
    "Burleigh Heads",
    "Burnett Heads",
    "Burnie",
    "Burnley",
    "Burnside",
    "Burpengary",
    "Burradoo",
    "Burraneer",
    "Burrum",
    "Burrum Heads",
    "Burwood",
    "Burwood",
    "Bushland Beach",
    "Busselton",
    "Butchers Ridge",
    "Buxton",
    "Byford",
    "Byron Bay",
    "Caboolture",
    "Cairns",
    "Calen",
    "Calingiri",
    "Callala Bay",
    "Callington",
    "Caloundra",
    "Caltowie",
    "Camberwell",
    "Cambewarra",
    "Cambridge",
    "Camden",
    "Camden Haven",
    "Cammeray",
    "Campbell",
    "Campbellfield",
    "Campbelltown",
    "Campbelltown",
    "Campbelltown",
    "Camperdown",
    "Camperdown",
    "Canadian",
    "Canberra",
    "Cannington",
    "Cannonvale",
    "Canterbury",
    "Canterbury",
    "Canungra",
    "Capalaba",
    "Caragabal",
    "Caravonica",
    "Carbrook",
    "Cardiff",
    "Cardigan",
    "Cardinia",
    "Cardup",
    "Caringbah",
    "Carlingford",
    "Carlsruhe",
    "Carlton",
    "Carlton North",
    "Carlton South",
    "Carnarvon",
    "Carnegie",
    "Caroline Springs",
    "Carrick",
    "Carrington",
    "Carrum",
    "Carrum Downs",
    "Casino",
    "Casterton",
    "Castle Hill",
    "Castlecrag",
    "Castlemaine",
    "Caulfield",
    "Caulfield North",
    "Caulfield South",
    "Caversham",
    "Cawarral",
    "Cawongla",
    "Cedar Grove",
    "Ceduna",
    "Central Coast",
    "Cessnock",
    "Charlestown",
    "Chatswood",
    "Chatsworth Island",
    "Chelsea",
    "Cheltenham",
    "Chinchilla",
    "Chippendale",
    "Chipping Norton",
    "Christies",
    "Chullora",
    "Churchill",
    "City of Parramatta",
    "City of West Torrens",
    "Clare",
    "Clare",
    "Claremont",
    "Claremont",
    "Clarence Town",
    "Clareville",
    "Clarinda",
    "Clarkefield",
    "Clayton North",
    "Cleveland",
    "Clifton",
    "Clifton Hill",
    "Clifton Springs",
    "Clontarf",
    "Clontarf",
    "Closeburn",
    "Clovelly",
    "Clunes",
    "Clyde",
    "Clyde",
    "Clyde North",
    "Cobbitty",
    "Coburg",
    "Cockatoo",
    "Cockburn",
    "Coffs Harbour",
    "Colac",
    "Coleambally",
    "Coledale",
    "Coleraine",
    "Collaroy",
    "Collie",
    "Collingwood",
    "Collinsvale",
    "Colo",
    "Colo Vale",
    "Como",
    "Concord",
    "Condamine",
    "Condobolin",
    "Coniston",
    "Connells Point",
    "Coober Pedy",
    "Cooee",
    "Coogee",
    "Coogee",
    "Cook",
    "Cooktown",
    "Coolah",
    "Coolamon",
    "Coolangatta",
    "Cooloolabin",
    "Coolum",
    "Coolum Beach",
    "Coolup",
    "Cooma",
    "Coomera",
    "Coonawarra",
    "Coondoo",
    "Cooranbong",
    "Cooroy",
    "Coorparoo",
    "Cootamundra",
    "Copacabana",
    "Copmanhurst",
    "Corinda",
    "Corinthia",
    "Corio",
    "Corlette",
    "Coromandel Valley",
    "Corrimal",
    "Cotham",
    "Cottesloe",
    "Coutts Crossing",
    "Cowan",
    "Cowes",
    "Cowra",
    "Crafers",
    "Craigieburn",
    "Cranbourne",
    "Crawford",
    "Cremorne",
    "Cremorne",
    "Crescent Head",
    "Creswick",
    "Crib Point",
    "Cringila",
    "Cronulla",
    "Crookwell",
    "Crossley",
    "Crows Nest",
    "Crows Nest",
    "Croydon",
    "Croydon",
    "Croydon North",
    "Crystal Creek",
    "Cudlee Creek",
    "Cummins",
    "Cundletown",
    "Curl Curl",
    "Currumbin",
    "Cygnet",
    "Daceyville",
    "Daisy Hill",
    "Dakabin",
    "Dalby",
    "Dalkeith",
    "Dandenong",
    "Dapto",
    "Dardanup",
    "Darkan",
    "Darley",
    "Darling",
    "Darling Point",
    "Darlinghurst",
    "Darlington",
    "Darlington",
    "Darra",
    "Darwin",
    "Davidson",
    "Davistown",
    "Dawson",
    "Dayboro",
    "Daylesford",
    "Deagon",
    "Deakin",
    "Deception Bay",
    "Deepdene",
    "Deer Park",
    "Deloraine",
    "Denham",
    "Denman",
    "Dereel",
    "Derrimut",
    "Derwent",
    "Devonport",
    "Diamond Creek",
    "Diggers Rest",
    "Dilston",
    "Dimboola",
    "Dimbulah",
    "Dingley",
    "Dirranbandi",
    "Dodges Ferry",
    "Dolans Bay",
    "Don",
    "Doncaster",
    "Doncaster East",
    "Donnybrook",
    "Donvale",
    "Doonside",
    "Doreen",
    "Dorrigo",
    "Doubtful Creek",
    "Douglas",
    "Douglas Park",
    "Dover Heights",
    "Drayton",
    "Dromana",
    "Drouin",
    "Drouin South",
    "Drouin West",
    "Drummond Cove",
    "Drummoyne",
    "Drysdale",
    "Dubbo",
    "Dumbalk",
    "Dumbleyung",
    "Dundas",
    "Dundowran",
    "Dungog",
    "Dunkeld",
    "Dunmore",
    "Dunolly",
    "Dunsborough",
    "Dural",
    "Eagle Farm",
    "Eagle Heights",
    "Eagleby",
    "Eaglehawk",
    "Eaglemont",
    "Earlwood",
    "East Fremantle",
    "East Gosford",
    "East Maitland",
    "East Malvern",
    "Eastwood",
    "Eaton",
    "Ebbw Vale",
    "Ebenezer",
    "Echuca",
    "Echunga",
    "Eden",
    "Eden Park",
    "Edge Hill",
    "Edgecliff",
    "Edith",
    "Edithvale",
    "Edmonton",
    "Edwardstown",
    "Eight Mile Plains",
    "Elderslie",
    "Elizabeth",
    "Ellalong",
    "Ellangowan",
    "Ellendale",
    "Ellerslie",
    "Elsternwick",
    "Elsternwick",
    "Eltham",
    "Eltham North",
    "Elwood",
    "Emerald",
    "Emerald",
    "Empire Bay",
    "Emu Park",
    "Emu Plains",
    "Emu Vale",
    "Encounter Bay",
    "Endeavour",
    "Endeavour Hills",
    "Enfield",
    "Engadine",
    "Enmore",
    "Enoggera",
    "Epping",
    "Epping",
    "Erina",
    "Erskine",
    "Eschol",
    "Esk",
    "Esperance",
    "Essendon",
    "Ettalong Beach",
    "Eudlo",
    "Eudunda",
    "Eumundi",
    "Euroa",
    "Evandale",
    "Everton",
    "Exeter",
    "Exmouth",
    "Failford",
    "Fairfield",
    "Fairfield",
    "Fairview",
    "Fairy Meadow",
    "Fassifern",
    "Faulconbridge",
    "Fawkner",
    "Fern Tree",
    "Fern Tree Gully",
    "Ferndale",
    "Ferntree Gully",
    "Fernvale",
    "Ferny Creek",
    "Figtree",
    "Findon",
    "Fingal",
    "Fingal Bay",
    "Fitzroy",
    "Flemington",
    "Flinders",
    "Flinders",
    "Flynn",
    "Footscray",
    "Forbes",
    "Forest",
    "Forest Hill",
    "Forestville",
    "Forrest",
    "Forrest",
    "Forsayth",
    "Forster",
    "Foster",
    "Franklin",
    "Frankston",
    "Freeling",
    "Freemans Reach",
    "Fremantle",
    "Freshwater",
    "Fulham",
    "Fullerton",
    "Fyshwick",
    "Galston",
    "Garfield",
    "Gatton",
    "Gawler",
    "Gayndah",
    "Gaythorne",
    "Geelong",
    "Geelong West",
    "Gellibrand",
    "George Town",
    "Gepps Cross",
    "Geraldton",
    "Gerringong",
    "Gheerulla",
    "Gilberton",
    "Gilmore",
    "Gilston",
    "Gin Gin",
    "Girraween",
    "Gisborne",
    "Gladesville",
    "Gladstone",
    "Glass House Mountains",
    "Glebe",
    "Glen Huntly",
    "Glen Huon",
    "Glen Innes",
    "Glen Iris",
    "Glen Osmond",
    "Glen Waverley",
    "Glenbrook",
    "Glenburn",
    "Glenelg",
    "Glenfield",
    "Glengarry",
    "Glenhaven",
    "Glenorchy",
    "Glenorchy",
    "Glenore Grove",
    "Glenorie",
    "Glenreagh",
    "Glenroy",
    "Glenvale",
    "Glossodia",
    "Gloucester",
    "Golconda",
    "Gold Coast",
    "Golden Grove",
    "Goodna",
    "Goodwood",
    "Goolwa",
    "Goomeri",
    "Goonellabah",
    "Goornong",
    "Gooseberry Hill",
    "Gordon",
    "Gordon",
    "Gordonvale",
    "Gore Hill",
    "Gorokan",
    "Gosford",
    "Gosforth",
    "Gosnells",
    "Goulburn",
    "Gould",
    "Gowrie",
    "Gracemere",
    "Grafton",
    "Grandchester",
    "Grange",
    "Grant",
    "Grantham",
    "Granville",
    "Grassmere",
    "Gravesend",
    "Green Hill",
    "Green Point",
    "Greenbank",
    "Greendale",
    "Greensborough",
    "Greenvale",
    "Greenwich",
    "Gregadoo",
    "Grenfell",
    "Greta",
    "Griffith",
    "Grove",
    "Grovedale",
    "Guildford",
    "Guildford",
    "Gundaroo",
    "Gunnedah",
    "Gymea",
    "Gymea Bay",
    "Gympie",
    "Haberfield",
    "Hackham",
    "Haddon",
    "Hadspen",
    "Hagley",
    "Hahndorf",
    "Hall",
    "Hallam",
    "Hallett",
    "Halls Gap",
    "Hamilton",
    "Hamilton",
    "Hamilton",
    "Hamilton",
    "Hammond",
    "Hampton",
    "Hampton Park",
    "Happy Valley",
    "Harrington",
    "Harristown",
    "Harvey",
    "Hastings",
    "Hastings Point",
    "Hat Head",
    "Hawker",
    "Hawkesbury Heights",
    "Hawksburn",
    "Hawthorn",
    "Hawthorne",
    "Haymarket",
    "Hazelbrook",
    "Hazelwood",
    "Healesville",
    "Heathcote",
    "Heathcote",
    "Heathcote Junction",
    "Heatherton",
    "Heathmont",
    "Heddon Greta",
    "Heidelberg",
    "Helensburgh",
    "Helensvale",
    "Hendon",
    "Hepburn Springs",
    "Hervey Bay",
    "Hexham",
    "Highbury",
    "Highett",
    "Highfields",
    "Hill Top",
    "Hillcrest",
    "Hindmarsh",
    "Hobart",
    "Hoddles Creek",
    "Hollow Tree",
    "Holroyd",
    "Holsworthy",
    "Homebush",
    "Homebush",
    "Hope Island",
    "Hope Valley",
    "Hopetoun",
    "Hoppers Crossing",
    "Hornsby",
    "Horsham",
    "Hove",
    "Howard",
    "Howard Springs",
    "Howden",
    "Howe",
    "Howlong",
    "Hughesdale",
    "Hunter",
    "Hunters Hill",
    "Huntly",
    "Huonville",
    "Hurstbridge",
    "Hurstville",
    "Hurstville Grove",
    "Hyland Park",
    "Illawarra",
    "Illawong",
    "Iluka",
    "Indented Head",
    "Ingham",
    "Ingle Farm",
    "Ingleburn",
    "Inglewood",
    "Innisfail",
    "Inverell",
    "Inverloch",
    "Invermay",
    "Ipswich",
    "Isabella",
    "Ivanhoe",
    "Ivanhoe East",
    "Ives",
    "Jacobs Well",
    "Jannali",
    "Jarrahdale",
    "Jensen",
    "Jilliby",
    "Jimboomba",
    "Jindabyne",
    "Jindivick",
    "Judbury",
    "Junee",
    "Kadina",
    "Kalgoorlie",
    "Kallista",
    "Kalorama",
    "Kambalda",
    "Kangaroo Flat",
    "Kangaroo Point",
    "Kanwal",
    "Kapunda",
    "Karalee",
    "Karana Downs",
    "Kardella",
    "Kardella South",
    "Kareela",
    "Karnup",
    "Karoonda",
    "Karratha",
    "Katherine",
    "Katoomba",
    "Kawungan",
    "Keilor",
    "Keiraville",
    "Keith",
    "Kellyville",
    "Kelmscott",
    "Kelso",
    "Kelvin Grove",
    "Kempsey",
    "Kempton",
    "Kendall",
    "Kenilworth",
    "Kenmore",
    "Kennington",
    "Kensington",
    "Kensington",
    "Kensington and Norwood",
    "Kenthurst",
    "Kenwick",
    "Kerang",
    "Kerry",
    "Keswick",
    "Kettering",
    "Kew",
    "Kew",
    "Kew East",
    "Keysborough",
    "Keysbrook",
    "Kiama",
    "Kilcoy",
    "Kilcunda",
    "Killara",
    "Killarney",
    "Killarney",
    "Killcare",
    "Killingworth",
    "Kilmore",
    "Kilsyth",
    "Kincumber",
    "Kindred",
    "Kingaroy",
    "Kinglake",
    "Kings Cross",
    "Kings Park",
    "Kingscliff",
    "Kingsthorpe",
    "Kingston",
    "Kingston",
    "Kingston",
    "Kingston",
    "Kingswood",
    "Kinross",
    "Kirrawee",
    "Kirribilli",
    "Kirwan",
    "Koah",
    "Kobble",
    "Koetong",
    "Kogarah",
    "Kojonup",
    "Koo-Wee-Rup",
    "Koolewong",
    "Koorawatha",
    "Koornalla",
    "Kootingal",
    "Kooyong",
    "Koroit",
    "Korumburra",
    "Kotara",
    "Kununurra",
    "Kuranda",
    "Kurnell",
    "Kurrajong Heights",
    "Kurri Kurri",
    "Kyabram",
    "Kyneton",
    "Kyogle",
    "Laang",
    "Laguna",
    "Laidley",
    "Lake Cathie",
    "Lake Heights",
    "Lake Illawarra",
    "Lake Munmorah",
    "Lakemba",
    "Lakes Entrance",
    "Lalor",
    "Lambton",
    "Lamington",
    "Lancefield",
    "Lancelin",
    "Landsborough",
    "Lane Cove",
    "Lang Lang",
    "Langhorne Creek",
    "Langley",
    "Langwarrin",
    "Lara",
    "Largs North",
    "Latrobe",
    "Lauderdale",
    "Launceston",
    "Laverton",
    "Laverton",
    "Lavington",
    "Lawgi",
    "Lawnton",
    "Lawson",
    "Lebrina",
    "Leeton",
    "Legana",
    "Leichhardt",
    "Lemon Tree Passage",
    "Lennox Head",
    "Leongatha",
    "Leopold",
    "Lethbridge",
    "Leumeah",
    "Leura",
    "Lewiston",
    "Lidcombe",
    "Lilli Pilli",
    "Lilydale",
    "Limestone",
    "Linden",
    "Lindenow",
    "Lindfield",
    "Lindisfarne",
    "Lisarow",
    "Lismore",
    "Lithgow",
    "Little Bay",
    "Little Hampton",
    "Little River",
    "Liverpool",
    "Loch",
    "Lockhart",
    "Lockridge",
    "Loftus",
    "Logan",
    "Logan City",
    "Logan Village",
    "Loganholme",
    "Loganlea",
    "Long Jetty",
    "Long Plains",
    "Long Point",
    "Longford",
    "Longreach",
    "Longueville",
    "Longwarry",
    "Lovely Banks",
    "Lowanna",
    "Lower Chittering",
    "Lower Plenty",
    "Lowood",
    "Loxton",
    "Luddenham",
    "Ludlow",
    "Lugarno",
    "Lulworth",
    "Lutana",
    "Lyndhurst",
    "Lyndoch",
    "Lyneham",
    "Lyons",
    "Lysterfield",
    "Macarthur",
    "Macedon",
    "Mackay",
    "Macksville",
    "Maclean",
    "Macleod",
    "Macquarie Park",
    "Maddington",
    "Maffra",
    "Magill",
    "Maidenwell",
    "Maitland",
    "Malabar",
    "Maleny",
    "Mallala",
    "Mallanganee",
    "Malmsbury",
    "Malvern",
    "Mandalong",
    "Mandurah",
    "Mangalore",
    "Mangerton",
    "Manildra",
    "Manjimup",
    "Manly",
    "Manly",
    "Mannering Park",
    "Manning",
    "Manning Point",
    "Mannum",
    "Mansfield",
    "Mapleton",
    "Mareeba",
    "Margaret River",
    "Margate",
    "Margate",
    "Marian",
    "Maribyrnong",
    "Marino",
    "Marion",
    "Marlee",
    "Marmor",
    "Marong",
    "Maroochydore",
    "Maroota",
    "Maroubra",
    "Marrickville",
    "Marsden",
    "Marsden Park",
    "Marshalltown",
    "Martins Creek",
    "Marulan",
    "Maryborough",
    "Maryborough",
    "Maryland",
    "Marysville",
    "Mascot",
    "Maslin Beach",
    "Matcham",
    "Matraville",
    "Maudsland",
    "Maybole",
    "Mayfield",
    "Maylands",
    "McCrae",
    "McGraths Hill",
    "McKinnon",
    "McLachlan",
    "McLaren Flat",
    "McLaren Vale",
    "Meadows",
    "Medlow Bath",
    "Medowie",
    "Melbourne",
    "Melrose",
    "Melton",
    "Melton South",
    "Melville",
    "Menai",
    "Menangle",
    "Mentone",
    "Meredith",
    "Merewether",
    "Meringandan",
    "Merlynston",
    "Mernda",
    "Merredin",
    "Merriwa",
    "Merrylands",
    "Middlemount",
    "Middleton",
    "Middleton",
    "Midway Point",
    "Mildura",
    "Mile End",
    "Miles",
    "Milton",
    "Miners Rest",
    "Minlaton",
    "Minmi",
    "Minto",
    "Miranda",
    "Mirani",
    "Mirboo",
    "Mirboo North",
    "Mirrabooka",
    "Mission Beach",
    "Mitcham",
    "Mitcham",
    "Mitchell",
    "Mitchelton",
    "Mitiamo",
    "Mittagong",
    "Moama",
    "Moana",
    "Modbury",
    "Moggill",
    "Mona Vale",
    "Monash",
    "Monbulk",
    "Mont Albert North",
    "Monteagle",
    "Monterey",
    "Montmorency",
    "Montrose",
    "Montville",
    "Mooloolaba",
    "Mooloolah Valley",
    "Moonah",
    "Moonee Ponds",
    "Mooney Mooney",
    "Moorabbin",
    "Mooralla",
    "Moore",
    "Moore Park",
    "Moorooduc",
    "Mooroolbark",
    "Mooroopna",
    "Mooroopna",
    "Moranbah",
    "Morang",
    "Morayfield",
    "Mordialloc",
    "Moree",
    "Moriac",
    "Morisset",
    "Mornington",
    "Morphett Vale",
    "Mortdale",
    "Mortlake",
    "Moruya",
    "Morwell",
    "Mosman",
    "Mosman Park",
    "Moss Vale",
    "Mossman",
    "Mount Barker",
    "Mount Colah",
    "Mount Cotton",
    "Mount Dandenong",
    "Mount Direction",
    "Mount Druitt",
    "Mount Egerton",
    "Mount Eliza",
    "Mount Evelyn",
    "Mount Gambier",
    "Mount Gravatt",
    "Mount Helen",
    "Mount Helena",
    "Mount Isa",
    "Mount Julian",
    "Mount Keira",
    "Mount Larcom",
    "Mount Lofty",
    "Mount Macedon",
    "Mount Martha",
    "Mount Molloy",
    "Mount Morgan",
    "Mount Ousley",
    "Mount Perry",
    "Mount Pleasant",
    "Mount Saint Thomas",
    "Mount Waverley",
    "Mount White",
    "Mourilyan",
    "Muchea",
    "Mudgee",
    "Mudgeeraba",
    "Mudjimba",
    "Mulgoa",
    "Mulgrave",
    "Mullewa",
    "Mullumbimby",
    "Mundaring",
    "Mundijong",
    "Murray Bridge",
    "Murrumba",
    "Murrumbateman",
    "Murrumbeena",
    "Murrurundi",
    "Murtoa",
    "Murwillumbah",
    "Muswellbrook",
    "Mylor",
    "Myrrhee",
    "Myrtleford",
    "Nagambie",
    "Nairne",
    "Nambour",
    "Nambucca Heads",
    "Nana Glen",
    "Nanango",
    "Nannup",
    "Napoleons",
    "Nar Nar Goon",
    "Narangba",
    "Narara",
    "Narellan",
    "Narooma",
    "Narrabeen",
    "Narrabri",
    "Narrandera",
    "Narrawong",
    "Narre Warren",
    "Narre Warren North",
    "Narrogin",
    "Narromine",
    "Neath",
    "Nebo",
    "Nedlands",
    "Neerim South",
    "Nelson Bay",
    "Nerang",
    "Nerrigundah",
    "Nerrina",
    "Neutral Bay",
    "New Farm",
    "New Lambton",
    "New Town",
    "Newcastle",
    "Newmarket",
    "Newnham",
    "Newport",
    "Newport",
    "Newry",
    "Newstead",
    "Newstead",
    "Newstead",
    "Newtown",
    "Newtown",
    "Nhill",
    "Nindaroo",
    "Ningi",
    "Nirranda",
    "Noarlunga",
    "Noble Park",
    "Noosa",
    "Noosaville",
    "Norah",
    "Nords Wharf",
    "Norlane",
    "Norman Park",
    "Normanhurst",
    "Normanton",
    "Normanville",
    "North Beach",
    "North Fitzroy",
    "North Mackay",
    "North Melbourne",
    "North Tamborine",
    "North Turramurra",
    "Northam",
    "Northcote",
    "Northgate",
    "Northmead",
    "Norton Summit",
    "Norwood",
    "Notting Hill",
    "Nowra",
    "Nullawarre",
    "Nunawading",
    "Nuriootpa",
    "Nyora",
    "Oak Park",
    "Oakdale",
    "Oakey",
    "Oakhurst",
    "Oaklands",
    "Oakleigh",
    "Oakleigh South",
    "Oatlands",
    "Oatley",
    "Oberon",
    "Obi Obi",
    "Ocean Shores",
    "Officer",
    "Old Bar",
    "Old Beach",
    "Olinda",
    "Oman-Ama",
    "One Tree Hill",
    "Orange",
    "Orchard Hills",
    "Orford",
    "Orient Point",
    "Ormeau",
    "Ormiston",
    "Ormond",
    "Orroroo",
    "Osborne",
    "Ourimbah",
    "Oxenford",
    "Oxley",
    "Oxley",
    "Oyster Bay",
    "Paddington",
    "Padstow",
    "Pakenham",
    "Pallarenda",
    "Palm Beach",
    "Palm Cove",
    "Palm Island",
    "Palmer",
    "Palmwoods",
    "Pambula",
    "Paradise",
    "Paramatta",
    "Parap",
    "Park Ridge",
    "Parkdale",
    "Parkerville",
    "Parkes",
    "Parkhurst",
    "Parkville",
    "Parkwood",
    "Pearce",
    "Pearcedale",
    "Pechey",
    "Pelican",
    "Pendle Hills",
    "Penfield",
    "Penguin",
    "Pennant Hills",
    "Penrith",
    "Penshurst",
    "Perenjori",
    "Perth",
    "Perth",
    "Peterborough",
    "Petrie",
    "Phillip",
    "Pialba",
    "Piawaning",
    "Picnic Bay",
    "Picton",
    "Piggabeen",
    "Pimpama",
    "Pine Mountain",
    "Pinery",
    "Pinjarra",
    "Pinkenba",
    "Pioneer",
    "Pipers Brook",
    "Pitt Town",
    "Pittsworth",
    "Plympton",
    "Point Clare",
    "Point Cook",
    "Point Lonsdale",
    "Point Lookout",
    "Point Pass",
    "Point Vernon",
    "Pokolbin",
    "Pomona",
    "Pontville",
    "Poowong",
    "Port Adelaide",
    "Port Augusta",
    "Port Douglas",
    "Port Fairy",
    "Port Hacking",
    "Port Hedland",
    "Port Kembla",
    "Port Lincoln",
    "Port MacDonnell",
    "Port Macquarie",
    "Port Melbourne",
    "Port Noarlunga",
    "Port Pirie",
    "Port Sorell",
    "Portarlington",
    "Portland",
    "Portsea",
    "Potts Point",
    "Prahran",
    "Preston",
    "Proserpine",
    "Prospect",
    "Purnim",
    "Pymble",
    "Pyrmont",
    "Quakers Hill",
    "Queanbeyan",
    "Queenscliff",
    "Queensferry",
    "Queenstown",
    "Railton",
    "Ramsgate",
    "Randwick",
    "Rathmines",
    "Ravenswood",
    "Raworth",
    "Raymond Terrace",
    "Red Hill",
    "Redan",
    "Redbank",
    "Redcliffe",
    "Redfern",
    "Redhead",
    "Redland Bay",
    "Redlynch",
    "Reedy Creek",
    "Regents Park",
    "Research",
    "Reservoir",
    "Retreat",
    "Revesby",
    "Reynella",
    "Rhodes",
    "Riana",
    "Richmond",
    "Richmond",
    "Riddell",
    "Ridgley",
    "Ringwood",
    "Ringwood East",
    "Ringwood North",
    "Ripley",
    "Risdon",
    "River Heads",
    "Riverside",
    "Riverstone",
    "Riverton",
    "Riverview",
    "Riverwood",
    "Robertson",
    "Robertstown",
    "Robinvale",
    "Rochedale",
    "Rochester",
    "Rockbank",
    "Rockdale",
    "Rockhampton",
    "Rockingham",
    "Rocklea",
    "Rodborough",
    "Rokeby",
    "Roleystone",
    "Roma",
    "Romsey",
    "Rooty Hill",
    "Rosanna",
    "Rose Bay",
    "Rosebery",
    "Rosebery",
    "Rosebud",
    "Rosehill",
    "Roseville",
    "Rosewood",
    "Roseworthy",
    "Ross",
    "Ross Creek",
    "Ross River",
    "Rowville",
    "Royal Park",
    "Rozelle",
    "Rudall",
    "Rushworth",
    "Rutherford",
    "Rydalmere",
    "Ryde",
    "Rye",
    "Rylstone",
    "Safety Bay",
    "Saint Albans",
    "Saint Andrews",
    "Saint George",
    "Saint Georges Basin",
    "Saint Helena",
    "Saint Ives",
    "Saint James",
    "Saint Leonards",
    "Saint Lucia",
    "Saint Marys",
    "Saint Peters",
    "Saints",
    "Salamander Bay",
    "Sale",
    "Salisbury",
    "Salt Ash",
    "Samford",
    "San Remo",
    "Sanctuary Point",
    "Sandford",
    "Sandgate",
    "Sandgate",
    "Sandringham",
    "Sandstone Point",
    "Sandy Bay",
    "Sandy Hollow",
    "Sans Souci",
    "Sapphire",
    "Sarina",
    "Sarina Beach",
    "Sassafras",
    "Scarborough",
    "Scarborough",
    "Scarness",
    "Scarsdale",
    "Schofields",
    "Scone",
    "Scoresby",
    "Scottsdale",
    "Seacliff",
    "Seacombe",
    "Seaford",
    "Seaford",
    "Seaforth",
    "Seaton",
    "Seaview",
    "Sebastopol",
    "Selbourne",
    "Selby",
    "Sellicks Beach",
    "Sellicks Hill",
    "Semaphore",
    "Serpentine",
    "Seven Hills",
    "Seven Mile Beach",
    "Seville",
    "Seville East",
    "Seymour",
    "Sheffield",
    "Shellharbour",
    "Shenton Park",
    "Sherbrook",
    "Shoal Point",
    "Shorncliffe",
    "Silvan",
    "Silverdale",
    "Silverwater",
    "Singleton",
    "Sippy Downs",
    "Slacks Creek",
    "Smithfield",
    "Smithfield",
    "Smithton",
    "Smythes Creek",
    "Smythesdale",
    "Snowtown",
    "Somersby",
    "Somerset",
    "Somerset",
    "Somerton",
    "Somerville",
    "Sorrento",
    "South Melbourne",
    "South Perth",
    "South West Rocks",
    "South Yarra",
    "Southbank",
    "Southern Brook",
    "Southport",
    "Spearwood",
    "Spencer",
    "Spotswood",
    "Spreyton",
    "Spring Field",
    "Spring Hill",
    "Spring Hill",
    "Springfield",
    "Springvale",
    "Springvale South",
    "Springwood",
    "St Helens",
    "St Kilda",
    "Stanhope",
    "Stanley",
    "Stanmore",
    "Stannum",
    "Stanthorpe",
    "Stapylton",
    "Stawell",
    "Stieglitz",
    "Stirling",
    "Stirling",
    "Stockton",
    "Stockyard Creek",
    "Stoneville",
    "Stradbroke",
    "Stratford",
    "Stratford",
    "Strathalbyn",
    "Strathfield",
    "Strathfieldsaye",
    "Strathmore",
    "Strathpine",
    "Streaky Bay",
    "Stroud",
    "Stuart Park",
    "Sturt",
    "Subiaco",
    "Success",
    "Suffolk Park",
    "Sulphur Creek",
    "Summerholm",
    "Summertown",
    "Sunbury",
    "Sunnybank",
    "Sunnyside",
    "Sunshine",
    "Surfers Paradise",
    "Surrey Hills",
    "Sutherland",
    "Swan Hill",
    "Swan View",
    "Swansea",
    "Swansea",
    "Sydenham",
    "Sydney",
    "Sylvania",
    "Sylvania Waters",
    "Tahmoor",
    "Tallangatta",
    "Tallarook",
    "Tallebudgera",
    "Talmalmo",
    "Tambo Upper",
    "Tamborine",
    "Tammin",
    "Tamworth",
    "Tannum Sands",
    "Tanunda",
    "Taree",
    "Taren Point",
    "Tarlee",
    "Tarneit",
    "Taroona",
    "Tarragindi",
    "Tarrawanna",
    "Tarro",
    "Tarzali",
    "Tatura",
    "Tawonga",
    "Teesdale",
    "Telegraph Point",
    "Temora",
    "Tempe",
    "Templestowe",
    "Templestowe Lower",
    "Tenambit",
    "Tennyson",
    "Tenterfield",
    "Teralba",
    "Terrigal",
    "Terry Hills",
    "Tewantin",
    "Thagoona",
    "Thargomindah",
    "The Basin",
    "The Entrance",
    "The Oaks",
    "The Patch",
    "The Rocks",
    "Thebarton",
    "Thirlmere",
    "Thirroul",
    "Thomastown",
    "Thompson",
    "Thornbury",
    "Thornlands",
    "Thornleigh",
    "Thornton",
    "Thuringowa",
    "Thursday Island",
    "Tiaro",
    "Tieri",
    "Tinamba",
    "Tincurrin",
    "Tingoora",
    "Tolga",
    "Tom Price",
    "Tomago",
    "Tongala",
    "Toogoolawah",
    "Toogoom",
    "Toolangi",
    "Toolern Vale",
    "Toongabbie",
    "Toora",
    "Tooradin",
    "Toorak",
    "Toorbul",
    "Tooronga",
    "Toowong",
    "Toowoomba",
    "Torbanlea",
    "Toronto",
    "Torquay",
    "Torquay",
    "Tottenham",
    "Toukley",
    "Townsville",
    "Towradgi",
    "Trafalgar",
    "Traralgon",
    "Traralgon South",
    "Trentham",
    "Trinity Beach",
    "Truganina",
    "Trunkey",
    "Tuggerah",
    "Tuggeranong",
    "Tugun",
    "Tullamarine",
    "Tully",
    "Tumut",
    "Tuncurry",
    "Tunnack",
    "Turners Beach",
    "Turramurra",
    "Tweed Heads",
    "Two Rocks",
    "Two Wells",
    "Tyabb",
    "Tyalgum",
    "Tynong",
    "Uki",
    "Ulladulla",
    "Ulmarra",
    "Ultimo",
    "Ulverstone",
    "Umina",
    "Unanderra",
    "Underwood",
    "Unley",
    "Upper Brookfield",
    "Upper Burringbar",
    "Upper Caboolture",
    "Upper Coomera",
    "Upwey",
    "Uraidla",
    "Urangan",
    "Valla Beach",
    "Valley Heights",
    "Vaucluse",
    "Venus Bay",
    "Verdun",
    "Vermont",
    "Victor Harbor",
    "Victoria Park",
    "Victoria Point",
    "Villawood",
    "Vineyard",
    "Virginia",
    "Virginia",
    "Waaia",
    "Wacol",
    "Wagga Wagga",
    "Wahgunyah",
    "Wahroonga",
    "Waikerie",
    "Waitara",
    "Walgett",
    "Walhalla",
    "Wallacia",
    "Wallan",
    "Wallaroo",
    "Wallington",
    "Walliston",
    "Wallsend",
    "Walmer",
    "Wamberal",
    "Wamuran",
    "Wanbi",
    "Wandin North",
    "Wandoan",
    "Wangaratta",
    "Wangi Wangi",
    "Wanneroo",
    "Wantirna",
    "Wantirna South",
    "Waratah",
    "Warburton",
    "Warnbro",
    "Warnervale",
    "Warragul",
    "Warrandyte",
    "Warrane",
    "Warrawong",
    "Warren",
    "Warren Shire",
    "Warrigal",
    "Warrimoo",
    "Warrnambool",
    "Warwick",
    "Waterford",
    "Waterloo",
    "Waterloo",
    "Waterloo",
    "Waterloo Corner",
    "Watsonia",
    "Wattle Grove",
    "Wattle Grove",
    "Waubra",
    "Wauchope",
    "Waurn Ponds",
    "Waverley",
    "Waverton",
    "Wayville",
    "Wedderburn",
    "Wedderburn",
    "Weetah",
    "Weethalle",
    "Wellard",
    "Wellington",
    "Wellington Point",
    "Welshpool",
    "Wembley",
    "Wendouree",
    "Wentworth",
    "Wentworth Falls",
    "Wentworthville",
    "Werribee",
    "Werribee South",
    "West Burleigh",
    "West End",
    "West Hoxton",
    "West Pymble",
    "West Wyalong",
    "Westbrook",
    "Westfield",
    "Westmead",
    "Weston",
    "Weston Creek",
    "Wheelers Hill",
    "White Rock",
    "Whitfield",
    "Whittlesea",
    "Whyalla",
    "Wickham",
    "Wickham",
    "Wilberforce",
    "Willaston",
    "Willaura",
    "Williams",
    "Williamstown",
    "Williamstown",
    "Willow Grove",
    "Willow Vale",
    "Willunga",
    "Wilmot",
    "Wilson",
    "Wilton",
    "Wiluna",
    "Wimbledon",
    "Winchelsea",
    "Windang",
    "Windaroo",
    "Windellama",
    "Windermere Park",
    "Windsor",
    "Windsor",
    "Windsor",
    "Windsor",
    "Windsor Downs",
    "Wingham",
    "Winkleigh",
    "Wodonga",
    "Wollar",
    "Wollert",
    "Wollongbar",
    "Wollongong",
    "Womboota",
    "Won Wron",
    "Wondai",
    "Wonga Park",
    "Wongan Hills",
    "Wonthaggi",
    "Woodburn",
    "Woodend",
    "Woodford",
    "Woodford",
    "Woodgate",
    "Woodleigh",
    "Woodridge",
    "Woodside",
    "Woodstock",
    "Woodvale",
    "Woodville",
    "Woolamai",
    "Woolgoolga",
    "Woolloomooloo",
    "Woolooware",
    "Wooloweyah",
    "Woolwich",
    "Woombah",
    "Woombye",
    "Woonona",
    "Woori Yallock",
    "Woorim",
    "Wooroolin",
    "Worongary",
    "Woronora",
    "Woy Woy",
    "Wulkuraka",
    "Wyalkatchem",
    "Wyalong",
    "Wyee",
    "Wyndham",
    "Wynnum",
    "Wynyard",
    "Wyong",
    "Wyongah",
    "Wyreema",
    "Yaamba",
    "Yackandandah",
    "Yallingup",
    "Yallourn",
    "Yallourn North",
    "Yamba",
    "Yanchep",
    "Yandina",
    "Yangan",
    "Yankalilla",
    "Yapeen",
    "Yaroomba",
    "Yarpturk",
    "Yarra Glen",
    "Yarra Junction",
    "Yarragon",
    "Yarram",
    "Yarraman",
    "Yarrambat",
    "Yarraville",
    "Yarrawarrah",
    "Yass",
    "Yatala",
    "Yea",
    "Yellow Rock",
    "Yenda",
    "Yeoval",
    "Yeppoon",
    "Yerrinbool",
    "Yinnar",
    "Yolla",
    "York",
    "Yorkeys Knob",
    "Young",
    "Yowie Bay",
    "Zeehan",
    "Absam",
    "Absdorf",
    "Abtenau",
    "Abtsdorf",
    "Ach",
    "Achenkirch",
    "Achensee",
    "Admont",
    "Adnet",
    "Afritz",
    "Aggsbach",
    "Aichbach",
    "Aichdorf",
    "Aifersdorf",
    "Aigen",
    "Aigen im Muehlkreis",
    "Ainet",
    "Aistersheim",
    "Alberndorf in der Riedmark",
    "Alberschwende",
    "Aldrans",
    "Alkoven",
    "Alland",
    "Allhartsberg",
    "Alpbach",
    "Altach",
    "Altenberg",
    "Altenberg bei Linz",
    "Altenburg",
    "Altendorf",
    "Altendorf",
    "Altenhof am Hausruck",
    "Altenmarkt an der Triesting",
    "Altenmarkt im Pongau",
    "Altheim",
    "Althofen",
    "Altlengbach",
    "Altlichtenwarth",
    "Altmunster",
    "Altwaidhofen",
    "Am See",
    "Amaliendorf",
    "Ampass",
    "Ampfelwang",
    "Amstetten",
    "Andorf",
    "Anger",
    "Anif",
    "Annenheim",
    "Ansfelden",
    "Anthering",
    "Apfelberg",
    "Arbesthal",
    "Ardagger Markt",
    "Ardning",
    "Arnoldstein",
    "Arriach",
    "Asberg",
    "Aschach an der Donau",
    "Aschau",
    "Aspang Markt",
    "Asparn",
    "Asperhofen",
    "Asten",
    "Attersee",
    "Attnang-Puchheim",
    "Atzbach",
    "Au",
    "Auersthal",
    "Aufhausen",
    "Augsdorf",
    "Aurolzmunster",
    "Axams",
    "Bach",
    "Bad Blumau",
    "Bad Deutsch-Altenburg",
    "Bad Erlach",
    "Bad Fischau",
    "Bad Gams",
    "Bad Gastein",
    "Bad Gleichenberg",
    "Bad Goisern",
    "Bad Hall",
    "Bad Hofgastein",
    "Bad Ischl",
    "Bad Kreuzen",
    "Bad Pirawarth",
    "Bad Radkersburg",
    "Bad Schallerbach",
    "Bad Tatzmannsdorf",
    "Bad Voslau",
    "Baden bei Wien",
    "Baernbach",
    "Baldramsdorf",
    "Bartholomaberg",
    "Barwies",
    "Bauer",
    "Baumgarten im Burgenland",
    "Baumgartenberg",
    "Baumkirchen",
    "Berg",
    "Bergau",
    "Bergheim",
    "Berndorf",
    "Bernhardsthal",
    "Bernstein",
    "Berwang",
    "Bezau",
    "Biberbach",
    "Biberwier",
    "Bichlbach",
    "Biedermann",
    "Biedermannsdorf",
    "Birgitz",
    "Bisamberg",
    "Bizau",
    "Bleiberg ob Villach",
    "Bleiburg",
    "Blindenmarkt",
    "Bludenz",
    "Bludesch",
    "Blumau",
    "Bockfliess",
    "Bodensdorf",
    "Boheimkirchen",
    "Bosendurnbach",
    "Bramberg am Wildkogel",
    "Brandberg",
    "Braunau am Inn",
    "Bregenz",
    "Breitenbrunn",
    "Breitenfurt bei Wien",
    "Breitenwang",
    "Brixen im Thale",
    "Bruck am Ziller",
    "Bruck an der Grossglocknerstrasse",
    "Bruck an der Leitha",
    "Bruck an der Mur",
    "Bruckl",
    "Bruckneudorf",
    "Bruendl",
    "Bruggen",
    "Brunn am Gebirge",
    "Buch",
    "Buch bei Jenbach",
    "Buchkirchen",
    "Burgkirchen",
    "Burgschleinitz",
    "Burmoos",
    "Dalaas",
    "Dechantskirchen",
    "Dellach",
    "Desselbrunn",
    "Deutsch Goritz",
    "Deutsch-Wagram",
    "Deutschfeistritz",
    "Deutschkreutz",
    "Deutschlandsberg",
    "Diepoltsham",
    "Dietach",
    "Dietersdorf am Gnasbach",
    "Dobersberg",
    "Dobersdorf",
    "Doblbach",
    "Dobldorf",
    "Doebriach",
    "Donnerskirchen",
    "Doren",
    "Dorf",
    "Dorfgastein",
    "Dorfla",
    "Dornbirn",
    "Drassburg",
    "Drassmarkt",
    "Dross",
    "Durnstein",
    "Ebbs",
    "Eben im Pongau",
    "Ebenau",
    "Ebendorf",
    "Ebenfurth",
    "Ebensee",
    "Ebenthal",
    "Ebergassing",
    "Eberndorf",
    "Eberschwang",
    "Ebersdorf",
    "Eberstein",
    "Ebreichsdorf",
    "Eckartsau",
    "Edelschrott",
    "Edelstal",
    "Edlitz",
    "Edt bei Lambach",
    "Eferding",
    "Egg",
    "Egg am Faaker See",
    "Eggenburg",
    "Eggendorf",
    "Eggendorf",
    "Eggendorf im Thale",
    "Eggersdorf bei Graz",
    "Ehrenhausen",
    "Ehrwald",
    "Eibiswald",
    "Eichgraben",
    "Eisbach",
    "Eisenberg",
    "Eisenerz",
    "Eisenstadt",
    "Eisentratten",
    "Eisgarn",
    "Elixhausen",
    "Ellmau",
    "Elsbethen",
    "Emberg",
    "Emmersdorf an der Donau",
    "Engelhartszell",
    "Engersdorf",
    "Engerwitzdorf",
    "Enns",
    "Ennsdorf",
    "Enzenkirchen",
    "Enzenreith",
    "Enzersdorf an der Fischa",
    "Enzersfeld",
    "Enzesfeld",
    "Erlauf",
    "Ernst",
    "Ernstbrunn",
    "Ernsthofen",
    "Erpersdorf",
    "Erpfendorf",
    "Esternberg",
    "Eugendorf",
    "Faak am See",
    "Falkenburg",
    "Fehring",
    "Feistritz",
    "Feistritz an der Drau",
    "Feld am See",
    "Feldbach",
    "Feldkirch",
    "Feldkirchen an der Donau",
    "Feldkirchen bei Graz",
    "Feldkirchen bei Mattighofen",
    "Feldkirchen in Karnten",
    "Felixdorf",
    "Ferndorf",
    "Fernitz",
    "Feuchten",
    "Feuersbrunn",
    "Fieberbrunn",
    "Filzmoos",
    "Finkenberg",
    "Finsing",
    "Fischamend Dorf",
    "Fischbach",
    "Fischerndorf",
    "Fiss",
    "Flachau",
    "Fladnitz im Raabtal",
    "Flattach",
    "Fliess",
    "Flinsdorf",
    "Foederlach",
    "Fohnsdorf",
    "Forst",
    "Frankenburg",
    "Frankenmarkt",
    "Frattingsdorf",
    "Frauenkirchen",
    "Freienstein",
    "Freilassing",
    "Freinberg",
    "Freistadt",
    "Friedburg",
    "Friesach",
    "Frohnleiten",
    "Fuernitz",
    "Fuerstenfeld",
    "Fugen",
    "Fulpmes",
    "Furthof",
    "Fusch an der Glocknerstrasse",
    "Fuschl am See",
    "Fussach",
    "Gaaden",
    "Gaal",
    "Gablitz",
    "Gaflenz",
    "Gailitz",
    "Gaisberg",
    "Gallbrunn",
    "Gallneukirchen",
    "Gallspach",
    "Gallzein",
    "Galtur",
    "Gaming",
    "Gampern",
    "Gansbach",
    "Ganserndorf",
    "Gargellen",
    "Gars am Kamp",
    "Garsten",
    "Gaschurn",
    "Gaspoltshofen",
    "Gasthof",
    "Gattendorf",
    "Gaweinstal",
    "Geinberg",
    "Geras",
    "Gerasdorf am Steinfelde",
    "Gerasdorf bei Wien",
    "Gerersdorf",
    "Gerlos",
    "Getzersdorf",
    "Gfohl",
    "Giesshubl",
    "Glan",
    "Glaubendorf",
    "Gleisdorf",
    "Glinzendorf",
    "Gloggnitz",
    "Gmund",
    "Gmunden",
    "Gnadenwald",
    "Gnas",
    "Gobelsburg",
    "Goedersdorf",
    "Goesselsdorf",
    "Gofis",
    "Going",
    "Goldegg",
    "Gollersdorf",
    "Golling an der Salzach",
    "Gols",
    "Gortipohl",
    "Gosau",
    "Gosdorf",
    "Gosing",
    "Gostling an der Ybbs",
    "Gotzendorf",
    "Gotzendorf an der Leitha",
    "Gotzens",
    "Gotzis",
    "Grabelsdorf",
    "Graen",
    "Grafenbach",
    "Grafendorf",
    "Grafendorf bei Hartberg",
    "Grafendorf bei Stainz",
    "Grafenschlag",
    "Grafenstein",
    "Grafenweg",
    "Grafenworth",
    "Gramastetten",
    "Gramatneusiedl",
    "Grambach",
    "Gratkorn",
    "Gratwein",
    "Graz",
    "Grein",
    "Gresten",
    "Gries",
    "Gries am Brenner",
    "Grieselstein",
    "Grieskirchen",
    "Griffen",
    "Grimmenstein",
    "Grobming",
    "Grodig",
    "Gross",
    "Gross-Enzersdorf",
    "Gross-Schweinbarth",
    "Gross-Siegharts",
    "Grossarl",
    "Grossebersdorf",
    "Grossklein",
    "Grosspesendorf",
    "Grossraming",
    "Grossrussbach",
    "Grossweikersdorf",
    "Grunbach am Schneeberg",
    "Gruner Baum",
    "Gschnitz",
    "Guessing",
    "Gugging",
    "Guglwald",
    "Gumpoldskirchen",
    "Gunselsdorf",
    "Gunskirchen",
    "Guntersdorf",
    "Guntramsdorf",
    "Gurten",
    "Gurtis",
    "Gutau",
    "Gutenstein",
    "Guttaring",
    "Haag",
    "Haag",
    "Haag am Hausruck",
    "Hadersdorf am Kamp",
    "Hadersfeld",
    "Hadres",
    "Hagenberg im Muhlkreis",
    "Haibach ob der Donau",
    "Haid",
    "Haidershofen",
    "Haiming",
    "Haimingerberg",
    "Hainburg an der Donau",
    "Hainfeld",
    "Halbturn",
    "Haldensee",
    "Hall",
    "Hall in Tirol",
    "Hallein",
    "Haller",
    "Hallstatt",
    "Harbach",
    "Hard",
    "Hart",
    "Hartberg",
    "Hartkirchen",
    "Haslau an der Donau",
    "Hatting",
    "Hatzendorf",
    "Haus",
    "Hausbrunn",
    "Hausleiten",
    "Hausmannstatten",
    "Hautzendorf",
    "Heidenreichstein",
    "Heiligenkreuz am Waasen",
    "Heimschuh",
    "Heissberg",
    "Heissingfelding",
    "Heiterwang",
    "Hellmonsodt",
    "Henndorf am Wallersee",
    "Hennersdorf",
    "Hermagor",
    "Hernstein",
    "Herrnbaumgarten",
    "Herzogenburg",
    "Herzogsdorf",
    "Himberg",
    "Himmelreich",
    "Hinterbruehl",
    "Hinterburg",
    "Hinterglemm",
    "Hintersdorf",
    "Hinterstoder",
    "Hinterthiersee",
    "Hintertux",
    "Hinterwaldberg",
    "Hipping",
    "Hirm",
    "Hirschegg",
    "Hirtenberg",
    "Hochburg",
    "Hochgurgl",
    "Hochleithen",
    "Hochneukirchen",
    "Hochsoelden",
    "Hochst",
    "Hoehe",
    "Hof am Leithaberge",
    "Hof bei Salzburg",
    "Hofen",
    "Hofkirchen im Traunkreis",
    "Hoflein",
    "Hofstatten an der Raab",
    "Hofstetten",
    "Hohenau",
    "Hohenberg",
    "Hohenburg",
    "Hoheneich",
    "Hohenems",
    "Hohentauern",
    "Hohenwarth",
    "Hohenzell",
    "Hohnhart",
    "Hollabrunn",
    "Hollenthon",
    "Hollersbach im Pinzgau",
    "Holzhausen",
    "Hopfgarten im Brixental",
    "Horbranz",
    "Horersdorf",
    "Horn",
    "Hornstein",
    "Horsching",
    "Huetten",
    "Huttschlag",
    "Igls",
    "Im Brand",
    "Imst",
    "Innerkrems",
    "Innermanzing",
    "Innsbruck",
    "Inzersdorf im Kremstal",
    "Inzing",
    "Ischgl",
    "Isper",
    "Jagenbach",
    "Jagerberg",
    "Japons",
    "Jeging",
    "Jenbach",
    "Jennersdorf",
    "Jerzens",
    "Jochberg",
    "Jois",
    "Judenau",
    "Judenburg",
    "Judendorf",
    "Jungholz",
    "Kainach bei Voitsberg",
    "Kaindorf",
    "Kalsdorf bei Graz",
    "Kaltenbrunn",
    "Kaltenleutgeben",
    "Kanzelhoehe",
    "Kapelln",
    "Kapfenberg",
    "Kapfing",
    "Kappern",
    "Kappl",
    "Kaprun",
    "Karl",
    "Karlstetten",
    "Karteis",
    "Katsdorf",
    "Katzelsdorf",
    "Kaumberg",
    "Kefermarkt",
    "Kematen in Tirol",
    "Kennelbach",
    "Keutschach am See",
    "Kienberg",
    "Kierling",
    "Kilb",
    "Kindberg",
    "Kirchbach in Steiermark",
    "Kirchberg am Wagram",
    "Kirchberg in Tirol",
    "Kirchbichl",
    "Kirchdorf an der Krems",
    "Kirchdorf in Tirol",
    "Kirchham",
    "Kirchschlag",
    "Kirchschlag bei Linz",
    "Kittsee",
    "Klagenfurt",
    "Klam",
    "Klaus",
    "Klein-Harras",
    "Kleinbergl",
    "Kleinkirchheim",
    "Kleinstubing",
    "Klingfurth",
    "Klosterle",
    "Klostermarienberg",
    "Klosterneuburg",
    "Knappenberg",
    "Knittelfeld",
    "Kobenz",
    "Kobersdorf",
    "Koblach",
    "Koestenberg",
    "Koetschach",
    "Koflach",
    "Kollmitzberg",
    "Konigstetten",
    "Konigswiesen",
    "Kopfing im Innkreis",
    "Koppl",
    "Korneuburg",
    "Kossen",
    "Kottingbrunn",
    "Kottmannsdorf",
    "Kraig",
    "Kramsach",
    "Krems",
    "Kremsbruecke",
    "Kremsdorf",
    "Kremsmunster",
    "Krenglbach",
    "Kreuz",
    "Krieglach",
    "Krispl",
    "Kritzendorf",
    "Kroatisch Minihof",
    "Krottendorf bei Ligist",
    "Krumbach",
    "Krumbach Markt",
    "Krumegg",
    "Krumpendorf",
    "Kuchl",
    "Kuehnsdorf",
    "Kuehtai",
    "Kufstein",
    "Kumberg",
    "Kundl",
    "Laa an der Thaya",
    "Laab im Walde",
    "Laaben",
    "Laakirchen",
    "Labach",
    "Lambrechten",
    "Lamprechtshausen",
    "Landeck",
    "Landegg",
    "Landskron",
    "Lanersbach",
    "Langeck im Burgenland",
    "Langenlois",
    "Langenrohr",
    "Langenstein",
    "Langenzersdorf",
    "Lannach",
    "Lanzenkirchen",
    "Lassee",
    "Lassnitzhohe",
    "Latschach",
    "Launsdorf",
    "Lauterach",
    "Lavamund",
    "Lavant",
    "Laxenburg",
    "Lebring",
    "Lech",
    "Lechaschau",
    "Leibnitz, Styria",
    "Leisach",
    "Leiten",
    "Leitring",
    "Lembach im Muhlkreis",
    "Lend",
    "Lendorf",
    "Lenzing",
    "Leoben",
    "Leobendorf",
    "Leobersdorf",
    "Leogang",
    "Leonding",
    "Leonfelden",
    "Leopoldsdorf",
    "Lermoos",
    "Leutasch",
    "Leutschach",
    "Lichtenau",
    "Lichtenberg",
    "Lichtenegg",
    "Lichtenworth",
    "Liebenfels",
    "Lieboch",
    "Lienz",
    "Liesfeld",
    "Liezen",
    "Ligist",
    "Lilienfeld",
    "Lindenberg",
    "Linz",
    "Litschau",
    "Lobenstein",
    "Lochau",
    "Lochen",
    "Lofer",
    "Lohnsburg",
    "Loimersdorf",
    "Loipersbach",
    "Loosdorf",
    "Loretto",
    "Ludesch",
    "Luftenberg an der Donau",
    "Lungotz",
    "Lustenau",
    "Lutzmannsburg",
    "Mader",
    "Madseit",
    "Maglern",
    "Maiersdorf",
    "Maildorf",
    "Mairhof",
    "Maissau",
    "Mallnitz",
    "Mandling",
    "Mank",
    "Mannersdorf am Leithagebirge",
    "Mannersdorf an der Rabnitz",
    "Mannsworth",
    "Marbach",
    "Marchegg",
    "Marchtrenk",
    "Margarethen am Moos",
    "Maria Alm am Steinernen Meer",
    "Maria Buch",
    "Maria Elend",
    "Maria Ellend",
    "Maria Enzersdorf",
    "Maria Lankowitz",
    "Maria Lanzendorf",
    "Maria Saal",
    "Maria Schmolln",
    "Maria Taferl",
    "Maria Worth",
    "Maria-Anzbach",
    "Mariazell",
    "Markgrafneusiedl",
    "Markt Allhau",
    "Markt Neuhodis",
    "Markt Piesting",
    "Marktl",
    "Marz",
    "Mathon",
    "Matrei am Brenner",
    "Matrei in Osttirol",
    "Mattersburg",
    "Mattsee",
    "Mauerbach",
    "Mauerkirchen",
    "Maurach",
    "Mauterndorf",
    "Mauthausen",
    "Mayrhofen",
    "Meggenhofen",
    "Mehrnbach",
    "Meiningen",
    "Meisten",
    "Melk",
    "Mellach",
    "Mettmach",
    "Michelbach Markt",
    "Micheldorf in Oberoesterreich",
    "Mieming",
    "Miesenbach",
    "Miesenbach",
    "Millstatt",
    "Mistelbach",
    "Mittelberg",
    "Mitterdorf im Muerztal",
    "Mitterkirchen im Machland",
    "Mitterndorf an der Fischa",
    "Mittersill",
    "Moellbruecke",
    "Mollersdorf",
    "Molln",
    "Mollram",
    "Monchhof",
    "Mondsee",
    "Moos",
    "Moosburg",
    "Moosdorf",
    "Mooskirchen",
    "Mosern",
    "Motz",
    "Muckendorf an der Donau",
    "Muerzhofen",
    "Muerzsteg",
    "Muerzzuschlag",
    "Muhlbach am Manhartsberg",
    "Munchendorf",
    "Muntlix",
    "Munzbach",
    "Munzkirchen",
    "Murau",
    "Murfeld",
    "Mutters",
    "Naarn im Machlande",
    "Nassereith",
    "Natternbach",
    "Nauders",
    "Neckenmarkt",
    "Neidling",
    "Nenzing",
    "Nesselwangle",
    "Nestelbach bei Graz",
    "Neudau",
    "Neudorf bei Landsee",
    "Neudorf bei Staatz",
    "Neudorfl",
    "Neufeld an der Leitha",
    "Neuhofen",
    "Neuhofen an der Krems",
    "Neuhofen an der Ybbs",
    "Neukirchen",
    "Neukirchen am Walde",
    "Neukirchen an der Enknach",
    "Neukirchen an der Vockla",
    "Neulengbach",
    "Neumarkt am Wallersee",
    "Neumarkt an der Ybbs",
    "Neumarkt im Hausruckkreis",
    "Neumarkt im Muhlkreis",
    "Neumarkt in Steiermark",
    "Neunkirchen",
    "Neusiedl am See",
    "Neusiedl bei Guessing",
    "Neustift",
    "Neutal",
    "Neuzeug",
    "Nickelsdorf",
    "Niederachen",
    "Niederalm",
    "Niederdorf",
    "Niederkreuzstetten",
    "Niederland",
    "Niederleis",
    "Niederndorf",
    "Niederneukirchen",
    "Niederwaldkirchen",
    "Niederwolz",
    "Nochling",
    "Nussdorf",
    "Nussdorf am Haunsberg",
    "Nuziders",
    "Obdach",
    "Ober-Grafendorf",
    "Oberaich",
    "Oberaichwald",
    "Oberalm",
    "Oberau",
    "Obergruenburg",
    "Obergurgl",
    "Oberhausen",
    "Oberhofen im Inntal",
    "Oberkappel",
    "Oberkirchbach",
    "Oberkohlstaetten",
    "Obernberg",
    "Obernberg am Brenner",
    "Oberndorf an der Melk",
    "Oberndorf bei Salzburg",
    "Oberneukirchen",
    "Oberort",
    "Oberperfuss",
    "Oberpullendorf",
    "Oberrohrbach",
    "Oberschutzen",
    "Obersdorf",
    "Obersiebenbrunn",
    "Obertauern",
    "Obertrum am See",
    "Obervellach",
    "Oberwaltersdorf",
    "Oberwart",
    "Oberweis",
    "Oberwolbling",
    "Obritzberg",
    "Obsteig",
    "Oed",
    "Oehling",
    "Oepping",
    "Oetz",
    "OEtztal-Bahnhof",
    "Offenhausen",
    "Oftering",
    "Oggau",
    "Ohlsdorf",
    "Ollern",
    "Opponitz",
    "Ort im Innkreis",
    "Orth an der Donau",
    "Oslip",
    "Ossiach",
    "Ostermiething",
    "Ottendorf bei Gleisdorf",
    "Ottenheim",
    "Ottensheim",
    "Pabneukirchen",
    "Pachfurth",
    "Paldau",
    "Panzendorf",
    "Parndorf",
    "Parschlug",
    "Pasching",
    "Passail",
    "Passthurn",
    "Patsch",
    "Pattergassen",
    "Payerbach",
    "Peggau",
    "Perchtoldsdorf",
    "Perg",
    "Pernegg an der Mur",
    "Pernitz",
    "Pertisau",
    "Perwang am Grabensee",
    "Petersdorf",
    "Petronell-Carnuntum",
    "Pettenbach",
    "Pettnau",
    "Pettneu",
    "Petzenkirchen",
    "Peuerbach",
    "Pfaffstatten",
    "Pfons",
    "Pfunds",
    "Piberbach",
    "Pichl",
    "Pichl bei Wels",
    "Pichling bei Stainz",
    "Piesendorf",
    "Pillberg",
    "Pillichsdorf",
    "Pinggau",
    "Pinkafeld",
    "Pinsdorf",
    "Piringsdorf",
    "Pirka",
    "Pischeldorf",
    "Pischelsdorf am Engelbach",
    "Pischelsdorf in Steiermark",
    "Pitten",
    "Plangeross",
    "Plankenau",
    "Plescherken",
    "Pochlarn",
    "Poelten",
    "Poertschach am Woerthersee",
    "Poetting",
    "Poggstall",
    "Polfing",
    "Pottelsdorf",
    "Pottenbrunn",
    "Pottendorf",
    "Pottenstein",
    "Pottsching",
    "Potzneusiedl",
    "Poysbrunn",
    "Poysdorf",
    "Prabach",
    "Pram",
    "Preding",
    "Pregarten",
    "Pressbaum",
    "Prinzersdorf",
    "Puch",
    "Puch bei Hallein",
    "Puchberg am Schneeberg",
    "Puchenau",
    "Pucking",
    "Purbach",
    "Purbach am Neusiedlersee",
    "Purgg",
    "Purgstall",
    "Purgstall",
    "Purkersdorf",
    "Pyhra",
    "Raab",
    "Raaba",
    "Raabs an der Thaya",
    "Radfeld",
    "Radstadt",
    "Ramsau im Zillertal",
    "Randegg",
    "Rangersdorf",
    "Rankweil",
    "Rannersdorf",
    "Rappoltenkirchen",
    "Rauchenwarth",
    "Rauris",
    "Redlham",
    "Regau",
    "Regelsbrunn",
    "Reichenau an der Rax",
    "Reichenau im Muhlkreis",
    "Reichendorf",
    "Reichraming",
    "Reifnitz",
    "Reisenberg",
    "Reitdorf",
    "Reith",
    "Reith bei Seefeld",
    "Reith im Alpbachtal",
    "Rekawinkel",
    "Reutte",
    "Ried im Innkreis",
    "Ried im Traunkreis",
    "Ried im Zillertal",
    "Ried in der Riedmark",
    "Riedenthal",
    "Rieding",
    "Riedlingsdorf",
    "Riefensberg",
    "Riegersburg",
    "Riezlern",
    "Ringelsdorf",
    "Rinn",
    "Rohrau",
    "Rohrbach am Kulm",
    "Rohrbach am Steinfelde",
    "Rohrbach in Oberosterreich",
    "Rohrmoos",
    "Roppen",
    "Rosegg",
    "Rosenau am Hengstpass",
    "Rosenbach",
    "Rosental",
    "Rosental",
    "Rotenbach",
    "Rothis",
    "Rotholz",
    "Rottenbach",
    "Rottenmann",
    "Rubring",
    "Ruden",
    "Rudersdorf",
    "Rum",
    "Rutzenmoos",
    "Saalbach",
    "Saalfelden am Steinernen Meer",
    "Sachendorf",
    "Sachsenburg",
    "Saint Anton",
    "Salzburg",
    "Sankt Agatha",
    "Sankt Andra am Zicksee",
    "Sankt Andrae",
    "Sankt Florian",
    "Sankt Gallenkirch",
    "Sankt Georgen am Ybbsfelde",
    "Sankt Georgen im Attergau",
    "Sankt Johann im Pongau",
    "Sankt Kanzian",
    "Sankt Kathrein am Hauenstein",
    "Sankt Lorenzen",
    "Sankt Lorenzen im Muerztal",
    "Sankt Margarethen im Burgenland",
    "Sankt Marienkirchen am Hausruck",
    "Sankt Martin am Techelsberg",
    "Sankt Martin am Ybbsfelde",
    "Sankt Michael im Burgenland",
    "Sankt Michael in Obersteiermark",
    "Sankt Oswald",
    "Sankt Pankraz",
    "Sankt Peter",
    "Sankt Polten",
    "Sankt Ruprecht an der Raab",
    "Sankt Stefan im Rosental",
    "Sankt Ulrich bei Steyr",
    "Sankt Valentin",
    "Sankt Veit an der Glan",
    "Sankt Veit im Pongau",
    "Sankt Wolfgang",
    "Sankt Wolfgang",
    "Sarleinsbach",
    "Satteins",
    "Sauerbrunn",
    "Sausenstein",
    "Schachendorf",
    "Schalchen",
    "Schardenberg",
    "Scharding",
    "Scharnstein",
    "Scharten",
    "Schattendorf",
    "Scheffau am Wilden Kaiser",
    "Scheifling",
    "Schiefling am See",
    "Schladming",
    "Schleinbach",
    "Schlierbach",
    "Schlins",
    "Schlitters",
    "Schmirn",
    "Schneeberg",
    "Schoenau",
    "Schoenberg im Stubaital",
    "Schoerfling",
    "Schonbuhel an der Donau",
    "Schongrabern",
    "Schonkirchen",
    "Schoppernau",
    "Schrems",
    "Schruns",
    "Schutzen am Gebirge",
    "Schwadorf",
    "Schwaigs",
    "Schwanberg",
    "Schwanenstadt",
    "Schwarzach",
    "Schwarzach im Pongau",
    "Schwarzau am Steinfelde",
    "Schwarzau im Gebirge",
    "Schwarzenau",
    "Schwarzenberg am Boehmerwald",
    "Schwaz",
    "Schwechat",
    "Schweiggers",
    "Schwendau",
    "Schwertberg",
    "Schwoich",
    "Sebersdorf",
    "Seckau",
    "Seeboden",
    "Seefeld in Tirol",
    "Seeham",
    "Seekirchen am Wallersee",
    "Seewalchen",
    "Seiersberg",
    "Seitenstetten Markt",
    "Semmering",
    "Semriach",
    "Serfaus",
    "Sernau",
    "Sibratsgfall",
    "Siebenhirten",
    "Siebenhirten",
    "Siegendorf im Burgenland",
    "Sieghartskirchen",
    "Sierndorf",
    "Sierning",
    "Siezenheim",
    "Sillian",
    "Silz",
    "Sinabelkirchen",
    "Sinnersdorf",
    "Sipbachzell",
    "Sirnitz",
    "Sistrans",
    "Sitzenberg",
    "Solden",
    "Soll",
    "Sollenau",
    "Sommerein",
    "Sooss",
    "Spielberg bei Knittelfeld",
    "Spillern",
    "Spital am Pyhrn",
    "Spittal an der Drau",
    "Spitz",
    "Spratzern",
    "Staatz",
    "Stadelbach",
    "Stadl-Paura",
    "Stadtschlaining",
    "Stainz",
    "Stainz bei Straden",
    "Stams",
    "Stans",
    "Stattegg",
    "Statzendorf",
    "Steg",
    "Stegersbach",
    "Stein an der Donau",
    "Stein an der Enns",
    "Stein im Jauntal",
    "Steinabruckl",
    "Steinach am Brenner",
    "Steinakirchen am Forst",
    "Steinberg bei Ligist",
    "Steindorf am Ossiacher See",
    "Steinerberg",
    "Steinerkirchen an der Traun",
    "Steinfeld",
    "Steinhaus",
    "Steinhaus am Semmering",
    "Stettenhof",
    "Steyr",
    "Steyregg",
    "Stiegl",
    "Stockerau",
    "Stoob",
    "Straden",
    "Strass",
    "Strassen",
    "Strassengel",
    "Strasshof an der Nordbahn",
    "Strasswalchen",
    "Strau",
    "Strobl",
    "Stubach",
    "Stubenberg",
    "Studenzen",
    "Stuhlfelden",
    "Stuhlsdorf",
    "Stumm",
    "Stummerberg",
    "Sulz",
    "Sulz im Wienerwald",
    "Sulzau",
    "Sulzberg",
    "Tadten",
    "Tal",
    "Tamsweg",
    "Tannheim",
    "Tarrenz",
    "Tattendorf",
    "Taufkirchen an der Pram",
    "Taufkirchen an der Trattnach",
    "Tauplitz",
    "Taxenbach",
    "Telfes im Stubai",
    "Telfs",
    "Ternberg",
    "Ternitz",
    "Teufenbach",
    "Thal",
    "Thalgau",
    "Thalheim bei Wels",
    "Thalling",
    "Thaur",
    "Thaya",
    "Theresienfeld",
    "Thoerl",
    "Thuringen",
    "Tiefenbach",
    "Tiefgraben",
    "Tieschen",
    "Tirol",
    "Tobaj",
    "Toeschling",
    "Toesenssteinach",
    "Traboch",
    "Traisen",
    "Traiskirchen",
    "Traismauer",
    "Trasdorf",
    "Traun",
    "Traunkirchen",
    "Traunstein",
    "Trausdorf an der Wulka",
    "Trautmannsdorf an der Leitha",
    "Tribuswinkel",
    "Trieben",
    "Tristach",
    "Troepolach",
    "Trofaiach",
    "Trumau",
    "Tschagguns",
    "Tschoeran",
    "Tulln",
    "Tullnerbach-Lawies",
    "Tumeltsham",
    "Turnitz",
    "Turrach",
    "Tweng",
    "Uderns",
    "Ulmerfeld",
    "Ulrichsberg",
    "Ulrichskirchen",
    "Ungenach",
    "Unterberg",
    "Untergrub",
    "Unterjoch",
    "Unterlamm",
    "Unterparschenbrunn",
    "Unterpremstatten",
    "Unterpullendorf",
    "Unterpurkla",
    "Unterradlberg",
    "Unterrohr",
    "Unterrohr",
    "Untersiebenbrunn",
    "Unterwaltersdorf",
    "Unterweitersdorf",
    "Unzmarkt",
    "Uttendorf",
    "Utzenaich",
    "Veitsch",
    "Velden am Woerthersee",
    "Vent",
    "Vienna",
    "Vigaun",
    "Viktorsberg",
    "Viktring",
    "Villach",
    "Virgen",
    "Vitis",
    "Vocklabruck",
    "Vocklamarkt",
    "Voelkermarkt",
    "Voitsberg",
    "Volders",
    "Vols",
    "Vorau",
    "Vorchdorf",
    "Vorderlanersbach",
    "Vordernberg",
    "Vosendorf",
    "Wagna",
    "Wagrain",
    "Waidhofen an der Thaya",
    "Waidhofen an der Ybbs",
    "Waidmannsfeld",
    "Waidring",
    "Waizenkirchen",
    "Walbersdorf",
    "Walchsee",
    "Wald am Arlberg",
    "Waldenstein",
    "Walding",
    "Waldkirchen am Wesen",
    "Waldzell",
    "Wallern an der Trattnach",
    "Wallern im Burgenland",
    "Wallsee",
    "Wals",
    "Waltersdorf an der March",
    "Waltersdorf in Oststeiermark",
    "Wampersdorf",
    "Wang",
    "Wangle",
    "Wartberg",
    "Wartberg an der Krems",
    "Warth",
    "Warth",
    "Wattens",
    "Watzelsdorf",
    "Watzendorf",
    "Waxenberg",
    "Weibern",
    "Weiden am See",
    "Weigelsdorf",
    "Weikendorf",
    "Weikersdorf am Steinfelde",
    "Weilbach",
    "Weiler",
    "Weinburg am Sassbach",
    "Weissbriach",
    "Weissenbach am Lech",
    "Weissenkirchen in der Wachau",
    "Weisskirchen an der Traun",
    "Weisskirchen in Steiermark",
    "Weiten",
    "Weitersfeld",
    "Weitra",
    "Weiz",
    "Wels",
    "Weng bei Admont",
    "Weng im Innkreis",
    "Wenns",
    "Weppersdorf",
    "Werfen",
    "Werfenweng",
    "Werndorf",
    "Wernstein am Inn",
    "Westendorf",
    "Wettmannstatten",
    "Wiener Neudorf",
    "Wiener Neustadt",
    "Wienerherberg",
    "Wies",
    "Wieselburg",
    "Wiesing",
    "Wiesmath",
    "Wieting",
    "Wildon",
    "Wilfleinsdorf",
    "Wilhelmsburg",
    "Wilhering",
    "Wimpassing an der Leitha",
    "Wimpassing im Schwarzatale",
    "Winden am See",
    "Windischgarsten",
    "Winkl",
    "Winzendorf",
    "Woelfnitz",
    "Wolfau",
    "Wolfpassing",
    "Wolfsberg",
    "Wolfsgraben",
    "Wolfurt",
    "Wolkersdorf im Weinviertel",
    "Wollersdorf",
    "Wordern",
    "Worgl",
    "Wulkaprodersdorf",
    "Wundschuh",
    "Wurflach",
    "Wurmbrand",
    "Ybbs an der Donau",
    "Ybbsitz",
    "Zams",
    "Zeillern",
    "Zeiselmauer",
    "Zell am Moos",
    "Zell am See",
    "Zell am Ziller",
    "Zell an der Ybbs",
    "Zellerndorf",
    "Zeltweg",
    "Zemendorf",
    "Zettling",
    "Ziersdorf",
    "Zillingdorf",
    "Zillingtal",
    "Zipf",
    "Zirl",
    "Zistersdorf",
    "Zobing",
    "Zuers",
    "Zurndorf",
    "Zwentendorf",
    "Zwettl Stadt",
    "Zwolfaxing",
    "Baku",
    "Nakhchivan",
    "Quba",
    "Qusar",
    "Sulutapa",
    "Sumqayit",
    "Xirdalan",
    "Zurges",
    "Andros Town",
    "Dunmore Town",
    "Freeport",
    "Marsh Harbour",
    "Nassau",
    "Palmetto Point",
    "Spanish Wells",
    "Al Budayyi`",
    "Al Hadd",
    "Al Hamalah",
    "Al Janabiyah",
    "Al Markh",
    "Al Muharraq",
    "Bani Jamrah",
    "Barbar",
    "Jurdab",
    "Madinat `Isa",
    "Madinat Hamad",
    "Manama",
    "Oil City",
    "Sanabis",
    "Sanad",
    "Sitrah",
    "Tubli",
    "Kuala Lumpur"
  ];
}

class Currencies {
  static List<String?>? currencies = [
    "USD",
    "EUR",
    "GBP",
    "TRY",
    "SAR",
    "QAR",
    "AED",
    "KWD",
    "IQD",
    "OMR",
    "EGP",
    "CHF",
    "JPY",
    "AUD",
    "NZD",
    "CNY",
    "SGD",
    "RUB",
    "TWD",
    "INR",
    "IDR",
    "MYR",
    "KRW",
    "NOK",
    "PKR",
    "PHP",
    "JOD",
    "TUD",
    "LBP",
  ];
}

class CarMakeModel {
  static List<String?>? carMaker = [
    "Toyota",
    "Nissan",
    "Mazda",
    "Kia",
    "Mercedes",
    "BMW",
    "VolksVagen",
    "Hyundai",
   /* "Audi",
    "Subaru",
    'Rang Rover',
    "Rolls Roys",
    "Bently",
    "Aston Martin",
    "Hino",
    "Fiat",
    "Renault",
    "Pegaut",*/
  ];
  static List<String?>? carModel = [
    /*Toyota*/
    "Toyota Avalon",
    "Toyota Belta",
    "Toyota Camry",
    "Toyota Century",
    "Toyota Corolla",
    "Toyota Crown",
    "Toyota Etios",
    "Toyota Mirai",
    "Toyota Prius",
    "Toyota Vios/Yaris",
    "Toyota Agya",
    "Toyota Aqua",
    "Toyota Corolla",
    "Toyota GR Corolla",
    "Toyota Etios",
    "Toyota Glanza",
    "Toyota Passo",
    "Yaris (XP150)",
    "Yaris (XP210)",
    "Toyota GR Yaris",
    "Toyota 4Runner",
    "Toyota Aygo X",
    "Toyota bZ4X",
    "Toyota C-HR",
    "Corolla Cross",
    "FJ Cruiser",
    "Toyota Fortuner",
    "Toyota Harrier",
    "Toyota Venza",
    "Toyota Highlander",
    "Cruiser (J70)",
    "Cruiser (J300)",
    "Toyota Prado",
    "Toyota Raize",
    "Toyota RAV4",
    "Toyota Wildlander",
    "Toyota Rush",
    "Toyota Sequoia",
    "Urban Cruiser",
    "Yaris Cross",
    "Toyota Alphard",
    "Toyota Avanza",
    "Toyota Veloz",
    "Toyota Calya",
    "Toyota Innova",
    "Toyota Noah",
    "Toyota Voxy",
    "Toyota Roomy",
    "Toyota Rumion",
    "Toyota Sienna",
    "ProAce Verso",
    "ProAce City Verso",
    "Toyota Sienta",
    "Toyota HiAce",
    "Toyota ProAce",
    "ProAce City",
    "Toyota Probox",
    "Toyota TownAce",
    "Toyota Hilux",
    "Cruiser (J70)",
    "Toyota Tacoma",
    "Toyota Tundra",
    "Toyota TownAce",
    "Toyota GR86",
    "Toyota Supra",
    "Toyota C+pod",
    "Toyota COMS",
    "Copen GR Sport",
    "Pixis Epoch",
    "Pixis Joy",
    "Pixis Mega",
    "Pixis Truck",
    "Pixis Van",
    "Toyota Coaster",
    "Toyota Dyna",
    "Toyota Sora",
    "Toyota JPN Taxi",
    /*Nissan*/
    "Nissan VERSA",
    "Nissan SENTRA",
    "Nissan ALTIMA",
    "Nissan MAXIMA",
    "Nissan LEAF",
    "370Z® COUPE",
    "Nissan GT-R",
    "Nissan KICKS",
    "ROGUE SPORT",
    "Nissan ROGUE",
    "Nissan MURANO",
    "Nissan PATHFINDER",
    "Nissan ARMADA",
    "Nissan FRONTIER",
    "Nissan TITAN",
    "Nissan TITAN XD",
    /*Mazda*/
    "MAZDA2",
    "MAZDA3",
    "MAZDA6",
    "MAZDA CX-3",
    "MAZDA CX-30",
    "MAZDA CX-5",
    "MAZDA CX-8",
    "MAZDA CX-9",
    "MAZDA MX-5",
    "MAZDA MX-5 RF",
    "MAZDA MX-30",
    "MAZDA BT-50",
    /*Kia*/
    "Kia Forte",
    "Kia K5",
    "Kia Rio",
    "Kia Soul",
    "Kia Stinger",
    "Kia EV6",
    "Kia Niro",
    "Kia Niro EV",
    "Kia Niro Hybrid",
    "Kia Seltos",
    "Kia Sorento",
    "Sorento Hybrid",
    "Sorento Plug-in Hybrid",
    "Kia Sportage",
    "Sportage Hybrid",
    "Kia Telluride",
    "Kia Carnival",
    "Kia Sedona",
    /*Mercedes*/
    "Mercedes S class",
    "Mercedes E class",
    "Mercedes C class",
    "Mercedes A class",
    "Mercedes B class",
    "Mercedes G class",
    "Mercedes CLS class",
    "Mercedes CLR class",
    "Mercedes AMG 57",
    "Mercedes AMG 63",
    /*BMW*/
    "BMW 100 series",
    "BMW 300 series",
    "BMW 500 series",
    "BMW 700 series",
    "BMW M3 series",
    "BMW M5 series",
    /*VolksVagen*/
    "VW Golf GTI",
    "VW Tiguan",
    "VW Atlas",
    "VW Taos",
    "VW Jetta",
    "VW Jetta GLI",
    "VW Passat",
    "VW Arteon",
    "VW Golf R",
    "VW Sedans",
    "VW Vento",
    "VW Bora",
    "VW Polo",
    "VW Touareg",
    "VW Amarok",
    "VW Caddy",
    "VW Touran",
    "VW Scirocco",
    "VW Sharan",
    "VW Taigo",
    "VW Nivus",
    /*Hyundai*/
    "Hyundai Azera",
    "Hyundai Sonata",
    "Veloster",
    "Hyundai i30",
    "Elantra",
    "Accent",
    "Hyundai i20",
    "Hyundai i10",
    "Palisade",
    "Santa Fe",
    "Tucson",
    "Creta",
    "Kona",
    "Venue",
    "Staria",
    "STARIA(Van)",
    "H-1",
    "H-100",
    "IONIQ 6",
    "IONIQ 5",
    "NEXO",
    "SantaFe Hybrid",
    "Tucson Hybrid",
    "Kona Electric",
    "Elantra Hybrid",
    "IONIQ Electric",
    "IONIQ Hybrid",
    /*Audi*/
    /*Subaru*/
    /*Rang Rover*/
    /*Rolls Roys*/
    /*Bently*/
    /*Aston Martin*/
    /*Hino*/
    /*Fiat*/
    /*Renault*/
    /*Pegout*/
  ];
}

class ProductsTypes {
  static List<String?>? vehicleCategory = [
    "Sedan",
    "SUV",
    "MPV",
    "Pickup",
    "Van",
    "Truck",
    "Bus",
    "Heavy",
  ];

  static List<String?>? realestatesForLiving = [
    "Apartment",
    "House",
    "Villa",
    "Building",
    "Ranch",
    "Land",
    "Office",
    "Shop",
    "Warehouse",
  ];

  static List<String?>? realestateRooms = [
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    '10+',
  ];

  static List<String?>? realestateFloors = [
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    '10',
    '11',
    '12',
    '13',
    '14',
    '15',
    '16',
    '17',
    '18',
    '19',
    '20',
    '21',
    '22',
    '23',
    '24',
    '25',
    '25+',
  ];

  static List<String?>? realestateSize = [
    '400sqf',
    '500sqf',
    '600sqf',
    '700sqf',
    '800sqf',
    '900sqf',
    '1000sqf',
    '1100sqf',
    '1200sqf',
    '1300sqf',
    '1400sqf',
    '1500sqf',
    '1600sqf',
    '1700sqf',
    '1800sqf',
    '1900sqf',
    '2000sqf',
    '2100sqf',
    '2200sqf',
    '2300sqf',
    '2400sqf',
    '2500sqf',
    '2600sqf',
    '2700sqf',
    '2800sqf',
    '2900sqf',
    '3000sqf',
    '3100sqf',
    '3200sqf',
    '3300sqf',
    '3400sqf',
    '3500sqf',
    '3600sqf',
    '3700sqf',
    '3800sqf',
    '3900sqf',
    '4000sqf',
    '4100sqf',
    '4200sqf',
    '4300sqf',
    '4400sqf',
    '4500sqf',
    '4600sqf',
    '4700sqf',
    '4800sqf',
    '4900sqf',
    '5000sqf',
    '5000+ ',
  ];

  static List<String?>? realestateFurnished = [
    'Fully Furnished',
    'Semi Furnished',
    'Not Furnished',
  ];

  static List<String?>? shipLengthList = [
    '20ft',
    '25ft',
    '30ft',
    '35ft',
    '40ft',
    '45ft',
    '50ft',
    '55ft',
    '60ft',
    '65ft',
    '70ft',
    '75ft',
    '80ft',
    '85ft',
    '90ft',
    '95ft',
    '100ft',
    '105ft',
    '110ft',
    '115ft',
    '120ft',
    '125ft',
    '130ft',
    '135ft',
    '140ft',
    '145ft',
    '150ft',
    '155ft',
    '160ft',
    '165ft',
    '170ft',
    '175ft',
    '180ft',
    '185ft',
    '190ft',
    '195ft',
    '200ft',
    '205ft',
    '210ft',
    '215ft',
    '220ft',
    '225ft',
    '230ft',
    '235ft',
    '240ft',
    '245ft',
    '250ft',
    '255ft',
    '260ft',
    '265ft',
    '270ft',
    '275ft',
    '280ft',
    '285ft',
    '290ft',
    '295ft',
    '300ft',
    '305ft',
    '310ft',
    '320ft',
    '320ft'
  ];
  static List<String?>? shipBeamList = [
    '10ft',
    '11ft',
    '12ft',
    '13ft',
    '14ft',
    '15ft',
    '16ft',
    '17ft',
    '18ft',
    '19ft',
    '20ft',
    '21ft',
    '22ft',
    '23ft',
    '24ft',
    '25ft',
    '26ft',
    '27ft',
    '28ft',
    '29ft',
    '30ft',
    '31ft',
    '32ft',
    '33ft'
  ];
  static List<String?>? shipWeightList = [
    '5-10 Ton',
    '11-15 Ton',
    '16-20 Ton',
    '21-25 Ton',
    '26-30 Ton',
    '31-35 Ton',
    '36-40 Ton',
    '41-45 Ton',
    '46-50 Ton',
    '51-55 Ton',
    '56-60 Ton',
    '61-65 Ton',
    '66-70 Ton',
    '71-75 Ton',
    '76-80 Ton',
    '81-85 Ton',
    '86-90 Ton',
    '91-95 Ton',
    '96-100 Ton',
    '101-105 Ton',
    '106-110 Ton',
    '111-115 Ton',
    '116-120 Ton',
    '121-125 Ton',
  ];
  static double? shipBeam = 0.0;
  static double? shipGrossWeight = 0.0;
  static int? shipProductionYear = 0;
}

class ColorsNames {
  static List<String?>? colorsList = [
    "White",
    "Black",
    "Blue",
    "Green",
    "Red",
    "Orange",
    "Grey",
    "Yellow",
  ];
}
